/* automatically generated from sn-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (sn_dialog_ui)
#endif
#ifdef __GNUC__
static const char sn_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char sn_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.24\"/><requires lib=\"libxfce4ui-2\" version=\"4.17\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can-focus\">False</property><property nam"
  "e=\"icon-name\">edit-clear-symbolic</property></object><object class=\""
  "GtkImage\" id=\"image4\"><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">False</property><property name=\"icon-name\">w"
  "indow-close-symbolic</property></object><object class=\"GtkListStore\" "
  "id=\"items-store\"><columns><column type=\"GIcon\"/><column type=\"gcha"
  "rarray\"/><column type=\"gboolean\"/><column type=\"gchararray\"/></col"
  "umns></object><object class=\"GtkListStore\" id=\"legacy-items-store\">"
  "<columns><column type=\"GIcon\"/><column type=\"gchararray\"/><column t"
  "ype=\"gboolean\"/><column type=\"gchararray\"/></columns></object><obje"
  "ct class=\"GtkAdjustment\" id=\"size-adjustment\"><property name=\"uppe"
  "r\">64</property><property name=\"value\">22</property><property name=\""
  "step-increment\">1</property><property name=\"page-increment\">2</prope"
  "rty></object><object class=\"XfceTitledDialog\" id=\"dialog\"><property"
  " name=\"can-focus\">False</property><property name=\"title\" translatab"
  "le=\"yes\">Status Tray Items</property><property name=\"default-width\""
  ">425</property><property name=\"default-height\">575</property><propert"
  "y name=\"icon-name\">org.xfce.panel.systray</property><property name=\""
  "type-hint\">normal</property><child internal-child=\"vbox\"><object cla"
  "ss=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"orie"
  "ntation\">vertical</property><property name=\"spacing\">2</property><ch"
  "ild internal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\""
  "dialog-action_area2\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><child><object class=\"GtkButton\""
  " id=\"close-button\"><property name=\"label\" translatable=\"yes\">_Clo"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can-focus\">True</property><property name=\"receives-default\">True</pr"
  "operty><property name=\"image\">image4</property><property name=\"use-u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkButt"
  "on\" id=\"items-clear\"><property name=\"label\" translatable=\"yes\">C"
  "_lear Known Items</property><property name=\"visible\">True</property><"
  "property name=\"can-focus\">True</property><property name=\"receives-de"
  "fault\">True</property><property name=\"tooltip-text\" translatable=\"y"
  "es\">Resets the list of items and their visibility settings</property><"
  "property name=\"image\">image1</property><property name=\"use-underline"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">1</property><property name=\"secondary\">True</property><property n"
  "ame=\"non-homogeneous\">True</property></packing></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"pack-type\">end</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkBo"
  "x\" id=\"vbox1\"><property name=\"visible\">True</property><property na"
  "me=\"can-focus\">False</property><property name=\"border-width\">12</pr"
  "operty><property name=\"orientation\">vertical</property><property name"
  "=\"spacing\">18</property><child><object class=\"GtkFrame\" id=\"frame2"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"label-xalign\">0</property><propert"
  "y name=\"shadow-type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment2\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"top-padding\">6"
  "</property><property name=\"left-padding\">12</property><child><object "
  "class=\"GtkGrid\" id=\"icon_grid\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><child><object class"
  "=\"GtkRevealer\" id=\"revealer-icon-size\"><property name=\"visible\">T"
  "rue</property><property name=\"can-focus\">False</property><property na"
  "me=\"margin-top\">6</property><property name=\"reveal-child\">True</pro"
  "perty><child><object class=\"GtkBox\" id=\"hbox1\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"spacing\">12</property><child><object class=\"GtkLabel\" i"
  "d=\"label2\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><property name=\"hexpand\">True</property><"
  "property name=\"label\" translatable=\"yes\">_Fixed icon size (pixels):"
  "</property><property name=\"use-underline\">True</property><property na"
  "me=\"mnemonic-widget\">spinbutton-icon-size</property><property name=\""
  "xalign\">0</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkSpinButto"
  "n\" id=\"spinbutton-icon-size\"><property name=\"visible\">True</proper"
  "ty><property name=\"can-focus\">True</property><property name=\"halign\""
  ">end</property><property name=\"valign\">center</property><property nam"
  "e=\"adjustment\">size-adjustment</property><property name=\"numeric\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">1"
  "</property></packing></child></object></child></object><packing><proper"
  "ty name=\"left-attach\">0</property><property name=\"top-attach\">1</pr"
  "operty><property name=\"width\">2</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"auto_size_label\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"halign\">start</property><property name=\"hexpand\">True</pro"
  "perty><property name=\"label\" translatable=\"yes\">Adjust size _automa"
  "tically</property><property name=\"use-underline\">True</property></obj"
  "ect><packing><property name=\"left-attach\">0</property><property name="
  "\"top-attach\">0</property></packing></child><child><object class=\"Gtk"
  "Switch\" id=\"switch-auto-size\"><property name=\"visible\">True</prope"
  "rty><property name=\"can-focus\">True</property><property name=\"halign"
  "\">end</property><property name=\"valign\">center</property></object><p"
  "acking><property name=\"left-attach\">1</property><property name=\"top-"
  "attach\">0</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label1\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">Icons</property"
  "><attributes><attribute name=\"weight\" value=\"bold\"/></attributes></"
  "object></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkFrame\" id=\"fr"
  "ame1\"><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"label-xalign\">0</property><pro"
  "perty name=\"shadow-type\">none</property><child><object class=\"GtkAli"
  "gnment\" id=\"alignment1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"top-padding"
  "\">6</property><property name=\"left-padding\">12</property><child><obj"
  "ect class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"orie"
  "ntation\">vertical</property><property name=\"spacing\">6</property><ch"
  "ild><object class=\"GtkCheckButton\" id=\"checkbutton-single-row\"><pro"
  "perty name=\"label\" translatable=\"yes\">Arrange _items in a single ro"
  "w</property><property name=\"visible\">True</property><property name=\""
  "can-focus\">True</property><property name=\"receives-default\">False</p"
  "roperty><property name=\"tooltip-text\" translatable=\"yes\">If enabled"
  ", ensure that the items are laid out in a single row</property><propert"
  "y name=\"use-underline\">True</property><property name=\"draw-indicator"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkCheckButton\""
  " id=\"checkbutton-hide-new-items\"><property name=\"label\" translatabl"
  "e=\"yes\">_Hide items by default</property><property name=\"visible\">T"
  "rue</property><property name=\"can-focus\">True</property><property nam"
  "e=\"receives-default\">False</property><property name=\"tooltip-text\" "
  "translatable=\"yes\">When enabled, all new items will be marked as \"Hi"
  "dden\"</property><property name=\"use-underline\">True</property><prope"
  "rty name=\"draw-indicator\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">2</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"checkbutton-square-icons\"><property na"
  "me=\"label\" translatable=\"yes\">_Square items</property><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">True</propert"
  "y><property name=\"receives-default\">False</property><property name=\""
  "tooltip-text\" translatable=\"yes\">Item buttons will take a square whe"
  "n it\'s possible</property><property name=\"use-underline\">True</prope"
  "rty><property name=\"draw-indicator\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">2</property></packing></child></o"
  "bject></child></object></child><child type=\"label\"><object class=\"Gt"
  "kLabel\" id=\"label4\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">Behavior</property><attributes><attribute name=\"weight\""
  " value=\"bold\"/></attributes></object></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">2</property></packing></child><child><o"
  "bject class=\"GtkStackSwitcher\" id=\"items_stack_switcher\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"halign\">center</property><property name=\"stack"
  "\">items_stack</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">3</property></packing></child><child><object class=\"GtkStack"
  "\" id=\"items_stack\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><property name=\"transition-type\""
  ">slide-left-right</property><child><object class=\"GtkBox\" id=\"sn_box"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"orientation\">vertical</property><p"
  "roperty name=\"spacing\">18</property><child><object class=\"GtkFrame\""
  " id=\"sn_known_items\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"label-xalign\">"
  "0</property><property name=\"shadow-type\">none</property><child><objec"
  "t class=\"GtkAlignment\" id=\"sn_alignment\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"top-padding\">6</property><child><object class=\"GtkBox\" id=\"h"
  "box2\"><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"vexpand\">True</property><prope"
  "rty name=\"spacing\">6</property><child><object class=\"GtkScrolledWind"
  "ow\" id=\"scrolledwindow1\"><property name=\"visible\">True</property><"
  "property name=\"can-focus\">True</property><property name=\"hscrollbar-"
  "policy\">never</property><property name=\"shadow-type\">in</property><c"
  "hild><object class=\"GtkTreeView\" id=\"items-treeview\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">True</property"
  "><property name=\"model\">items-store</property><property name=\"header"
  "s-clickable\">False</property><property name=\"rules-hint\">True</prope"
  "rty><property name=\"enable-search\">False</property><child internal-ch"
  "ild=\"selection\"><object class=\"GtkTreeSelection\"/></child><child><o"
  "bject class=\"GtkTreeViewColumn\" id=\"treeviewcolumn-icon\"><property "
  "name=\"min-width\">24</property><child><object class=\"GtkCellRendererP"
  "ixbuf\" id=\"cellrendererpixbuf1\"><property name=\"stock_size\">1</pro"
  "perty></object><attributes><attribute name=\"gicon\">0</attribute></att"
  "ributes></child></object></child><child><object class=\"GtkTreeViewColu"
  "mn\" id=\"treeviewcolumn-name\"><property name=\"title\" translatable=\""
  "yes\">Item</property><property name=\"expand\">True</property><child><o"
  "bject class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attribut"
  "es><attribute name=\"text\">1</attribute></attributes></child></object>"
  "</child><child><object class=\"GtkTreeViewColumn\" id=\"treeviewcolumn-"
  "hidden\"><property name=\"title\" translatable=\"yes\">Hidden</property"
  "><child><object class=\"GtkCellRendererToggle\" id=\"hidden-toggle\"/><"
  "attributes><attribute name=\"active\">2</attribute></attributes></child"
  "></object></child></object></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkBox\" id=\"vbox5\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><property name=\"orientation\">ve"
  "rtical</property><child><object class=\"GtkButton\" id=\"item-up\"><pro"
  "perty name=\"visible\">True</property><property name=\"can-focus\">True"
  "</property><property name=\"receives-default\">True</property><property"
  " name=\"tooltip-text\" translatable=\"yes\">Move the selected item one "
  "row up</property><child><object class=\"GtkImage\" id=\"image2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property><property name=\"icon-name\">go-up-symbolic</property></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkButton\" id=\"item-d"
  "own\"><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">True</property><property name=\"receives-default\">True</property"
  "><property name=\"tooltip-text\" translatable=\"yes\">Move the selected"
  " item one row down</property><child><object class=\"GtkImage\" id=\"ima"
  "ge3\"><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">False</property><property name=\"icon-name\">go-down-symbolic</pr"
  "operty></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child><style><class name=\"linked\"/><"
  "/style></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">1</prope"
  "rty></packing></child></object></child></object></child><child type=\"l"
  "abel\"><object class=\"GtkLabel\" id=\"sn_known_items_label\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\">Known Items</prope"
  "rty><attributes><attribute name=\"weight\" value=\"bold\"/></attributes"
  "></object></child></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkFrame\" id=\"f"
  "rame3\"><property name=\"visible\">True</property><property name=\"can-"
  "focus\">False</property><property name=\"label-xalign\">0</property><pr"
  "operty name=\"shadow-type\">none</property><child><object class=\"GtkAl"
  "ignment\" id=\"alignment3\"><property name=\"visible\">True</property><"
  "property name=\"can-focus\">False</property><property name=\"top-paddin"
  "g\">6</property><property name=\"left-padding\">12</property><child><ob"
  "ject class=\"GtkBox\" id=\"vbox3\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"ori"
  "entation\">vertical</property><property name=\"spacing\">6</property><c"
  "hild><object class=\"GtkCheckButton\" id=\"checkbutton-menu-is-primary\""
  "><property name=\"label\" translatable=\"yes\">_Menu is primary action<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n-focus\">True</property><property name=\"receives-default\">False</pro"
  "perty><property name=\"tooltip-text\" translatable=\"yes\">Left click w"
  "ill always display the menu for item</property><property name=\"use-und"
  "erline\">True</property><property name=\"draw-indicator\">True</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"checkbutto"
  "n-symbolic-icons\"><property name=\"label\" translatable=\"yes\">_Reque"
  "st symbolic icons</property><property name=\"visible\">True</property><"
  "property name=\"can-focus\">True</property><property name=\"receives-de"
  "fault\">False</property><property name=\"tooltip-text\" translatable=\""
  "yes\">Load symbolic icons if available</property><property name=\"use-u"
  "nderline\">True</property><property name=\"draw-indicator\">True</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child></object></child></object></child><child type=\"labe"
  "l\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Features</property><attributes><att"
  "ribute name=\"weight\" value=\"bold\"/></attributes></object></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object><packing><property name=\"name\">Status Notifiers"
  "</property><property name=\"title\" translatable=\"yes\">Status Notifie"
  "rs</property></packing></child><child><object class=\"GtkFrame\" id=\"s"
  "ystray_frame\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"label-xalign\">0</prope"
  "rty><property name=\"shadow-type\">none</property><child><object class="
  "\"GtkAlignment\" id=\"systray_frame_alignment\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"top-padding\">6</property><child><object class=\"GtkBox\" id="
  "\"hbox3\"><property name=\"visible\">True</property><property name=\"ca"
  "n-focus\">False</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">True</prope"
  "rty><property name=\"hscrollbar-policy\">never</property><property name"
  "=\"shadow-type\">in</property><child><object class=\"GtkTreeView\" id=\""
  "legacy-items-treeview\"><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">True</property><property name=\"model\">legacy-"
  "items-store</property><property name=\"headers-clickable\">False</prope"
  "rty><property name=\"rules-hint\">True</property><property name=\"enabl"
  "e-search\">False</property><property name=\"search-column\">1</property"
  "><child internal-child=\"selection\"><object class=\"GtkTreeSelection\""
  "/></child><child><object class=\"GtkTreeViewColumn\" id=\"treeviewcolum"
  "n-legacy-icon\"><property name=\"min-width\">24</property><child><objec"
  "t class=\"GtkCellRendererPixbuf\" id=\"cellrendererpixbuf2\"><property "
  "name=\"stock_size\">1</property></object><attributes><attribute name=\""
  "gicon\">0</attribute></attributes></child></object></child><child><obje"
  "ct class=\"GtkTreeViewColumn\" id=\"treeviewcolumn-legacy-name\"><prope"
  "rty name=\"title\" translatable=\"yes\">Item</property><property name=\""
  "expand\">True</property><child><object class=\"GtkCellRendererText\" id"
  "=\"cellrenderertext2\"/><attributes><attribute name=\"text\">1</attribu"
  "te></attributes></child></object></child><child><object class=\"GtkTree"
  "ViewColumn\" id=\"treeviewcolumn-legacy-hidden\"><property name=\"title"
  "\" translatable=\"yes\">Hidden</property><child><object class=\"GtkCell"
  "RendererToggle\" id=\"legacy-hidden-toggle\"/><attributes><attribute na"
  "me=\"active\">2</attribute></attributes></child></object></child></obje"
  "ct></child></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkBox\" id=\"vbox6\"><"
  "property name=\"visible\">True</property><property name=\"can-focus\">F"
  "alse</property><property name=\"orientation\">vertical</property><child"
  "><object class=\"GtkButton\" id=\"legacy-item-up\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">True</property><prop"
  "erty name=\"receives-default\">True</property><property name=\"tooltip-"
  "text\" translatable=\"yes\">Move the selected item one row up</property"
  "><child><object class=\"GtkImage\" id=\"image5\"><property name=\"visib"
  "le\">True</property><property name=\"can-focus\">False</property><prope"
  "rty name=\"icon-name\">go-up-symbolic</property></object></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkButton\" id=\"legacy-item-down\"><pr"
  "operty name=\"visible\">True</property><property name=\"can-focus\">Tru"
  "e</property><property name=\"receives-default\">True</property><propert"
  "y name=\"tooltip-text\" translatable=\"yes\">Move the selected item one"
  " row down</property><child><object class=\"GtkImage\" id=\"image6\"><pr"
  "operty name=\"visible\">True</property><property name=\"can-focus\">Fal"
  "se</property><property name=\"icon-name\">go-down-symbolic</property></"
  "object></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child><style><class name=\"linked\"/></style></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object></child></object></child><child type=\"label\"><o"
  "bject class=\"GtkLabel\" id=\"systray_frame_label\"><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">Known Items</property><attri"
  "butes><attribute name=\"weight\" value=\"bold\"/></attributes></object>"
  "</child></object><packing><property name=\"name\">Systray Icons</proper"
  "ty><property name=\"title\" translatable=\"yes\">Systray Icons</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">4</property></packing></chi"
  "ld></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">1</property><"
  "/packing></child></object></child><action-widgets><action-widget respon"
  "se=\"0\">close-button</action-widget></action-widgets></object></interf"
  "ace>"
};

static const unsigned sn_dialog_ui_length = 22471u;

