/* automatically generated from clock-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (clock_dialog_ui)
#endif
#ifdef __GNUC__
static const char clock_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char clock_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.24\"/><requires lib=\"libxfce4ui-2\" version=\"4.17\"/"
  "><object class=\"GtkListStore\" id=\"binary-mode-model\"><columns><colu"
  "mn type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable"
  "=\"yes\">Decimal</col></row><row><col id=\"0\" translatable=\"yes\">Sex"
  "agesimal</col></row><row><col id=\"0\" translatable=\"yes\">Binary time"
  "</col></row></data></object><object class=\"GtkListStore\" id=\"digital"
  "-format-model\"><columns><column type=\"gchararray\"/></columns><data><"
  "row><col id=\"0\" translatable=\"yes\">Date, then time</col></row><row>"
  "<col id=\"0\" translatable=\"yes\">Time, then date</col></row><row><col"
  " id=\"0\" translatable=\"yes\">Date Only</col></row><row><col id=\"0\" "
  "translatable=\"yes\">Time Only</col></row></data></object><object class"
  "=\"GtkAdjustment\" id=\"fuzziness\"><property name=\"upper\">3</propert"
  "y><property name=\"step-increment\">1</property><property name=\"page-i"
  "ncrement\">1</property><property name=\"page-size\">1</property></objec"
  "t><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">T"
  "rue</property><property name=\"can-focus\">False</property><property na"
  "me=\"icon-name\">time-admin</property></object><object class=\"GtkImage"
  "\" id=\"image2\"><property name=\"visible\">True</property><property na"
  "me=\"can-focus\">False</property><property name=\"icon-name\">window-cl"
  "ose-symbolic</property></object><object class=\"GtkImage\" id=\"image3\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"icon-name\">help-browser</property></"
  "object><object class=\"GtkListStore\" id=\"mode-model\"><columns><colum"
  "n type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable="
  "\"yes\">Analog</col></row><row><col id=\"0\" translatable=\"yes\">Binar"
  "y</col></row><row><col id=\"0\" translatable=\"yes\">Digital</col></row"
  "><row><col id=\"0\" translatable=\"yes\">Fuzzy</col></row><row><col id="
  "\"0\" translatable=\"yes\">LCD</col></row></data></object><object class"
  "=\"XfceTitledDialog\" id=\"dialog\"><property name=\"can-focus\">False<"
  "/property><property name=\"title\" translatable=\"yes\">Clock</property"
  "><property name=\"icon-name\">org.xfce.panel.clock</property><property "
  "name=\"type-hint\">normal</property><child internal-child=\"vbox\"><obj"
  "ect class=\"GtkBox\" id=\"dialog-vbox2\"><property name=\"visible\">Tru"
  "e</property><property name=\"can-focus\">False</property><property name"
  "=\"orientation\">vertical</property><property name=\"spacing\">2</prope"
  "rty><child internal-child=\"action_area\"><object class=\"GtkButtonBox\""
  " id=\"dialog-action_area2\"><property name=\"visible\">True</property><"
  "property name=\"can-focus\">False</property><property name=\"layout-sty"
  "le\">end</property><child><object class=\"GtkButton\" id=\"close-button"
  "\"><property name=\"label\" translatable=\"yes\">_Close</property><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">True<"
  "/property><property name=\"receives-default\">True</property><property "
  "name=\"image\">image2</property><property name=\"use-underline\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkButton\" id=\"help-b"
  "utton\"><property name=\"label\" translatable=\"yes\">_Help</property><"
  "property name=\"visible\">True</property><property name=\"can-focus\">T"
  "rue</property><property name=\"receives-default\">True</property><prope"
  "rty name=\"image\">image3</property><property name=\"use-underline\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">1"
  "</property><property name=\"secondary\">True</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"pack-type\">end</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"bord"
  "er-width\">6</property><property name=\"orientation\">vertical</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkFram"
  "e\" id=\"frame2\"><property name=\"visible\">True</property><property n"
  "ame=\"can-focus\">False</property><property name=\"margin-bottom\">18</"
  "property><property name=\"label-xalign\">0</property><property name=\"s"
  "hadow-type\">none</property><child><object class=\"GtkGrid\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"margin-left\">18</property><property name=\"row-"
  "spacing\">6</property><property name=\"column-spacing\">12</property><c"
  "hild><object class=\"GtkEntry\" id=\"timezone-name\"><property name=\"v"
  "isible\">True</property><property name=\"can-focus\">True</property><pr"
  "operty name=\"hexpand\">True</property><property name=\"invisible-char\""
  ">\342\227\217</property><property name=\"secondary-icon-name\">help-con"
  "tents</property><property name=\"primary-icon-activatable\">False</prop"
  "erty><property name=\"secondary-icon-tooltip-text\" translatable=\"yes\""
  ">Name of a timezone corresponding a file in the zoneinfo database, for "
  "example \"America/New_York\". Leave empty to use the localtime.</proper"
  "ty></object><packing><property name=\"left-attach\">1</property><proper"
  "ty name=\"top-attach\">0</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</property"
  "><property name=\"can-focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">Time_zone:</property><property name=\"use-underlin"
  "e\">True</property><property name=\"xalign\">0</property></object><pack"
  "ing><property name=\"left-attach\">0</property><property name=\"top-att"
  "ach\">0</property></packing></child><child><object class=\"GtkButton\" "
  "id=\"run-time-config-tool\"><property name=\"label\" translatable=\"yes"
  "\">Time and Date _Settings...</property><property name=\"use-action-app"
  "earance\">False</property><property name=\"visible\">True</property><pr"
  "operty name=\"can-focus\">True</property><property name=\"receives-defa"
  "ult\">True</property><property name=\"image\">image1</property><propert"
  "y name=\"use-underline\">True</property></object><packing><property nam"
  "e=\"left-attach\">0</property><property name=\"top-attach\">1</property"
  "></packing></child></object></child><child type=\"label\"><object class"
  "=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</property><"
  "property name=\"can-focus\">False</property><property name=\"margin-bot"
  "tom\">6</property><property name=\"label\" translatable=\"yes\">Time Se"
  "ttings</property><attributes><attribute name=\"weight\" value=\"bold\"/"
  "></attributes></object></child></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kFrame\"><property name=\"visible\">True</property><property name=\"can"
  "-focus\">False</property><property name=\"margin-bottom\">18</property>"
  "<property name=\"label-xalign\">0</property><property name=\"shadow-typ"
  "e\">none</property><child><object class=\"GtkGrid\"><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">False</property><pr"
  "operty name=\"margin-left\">18</property><property name=\"row-spacing\""
  ">6</property><property name=\"column-spacing\">12</property><child><obj"
  "ect class=\"GtkEntry\" id=\"command\"><property name=\"visible\">True</"
  "property><property name=\"can-focus\">True</property><property name=\"h"
  "expand\">True</property><property name=\"invisible-char\">\342\227\217<"
  "/property><property name=\"secondary-icon-name\">help-contents</propert"
  "y><property name=\"primary-icon-activatable\">False</property><property"
  " name=\"secondary-icon-tooltip-text\" translatable=\"yes\">If set, this"
  " command is run when the plugin is left-clicked, instead of displaying "
  "the default calendar.</property></object><packing><property name=\"left"
  "-attach\">1</property><property name=\"top-attach\">1</property></packi"
  "ng></child><child><object class=\"GtkLabel\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Co_mmand:</property><property name="
  "\"use-underline\">True</property><property name=\"xalign\">0</property>"
  "</object><packing><property name=\"left-attach\">0</property><property "
  "name=\"top-attach\">1</property></packing></child><child><object class="
  "\"GtkCheckButton\" id=\"show-week-numbers\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Show week numbers</property><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">True</property><propert"
  "y name=\"receives-default\">False</property><property name=\"use-underl"
  "ine\">True</property><property name=\"draw-indicator\">True</property><"
  "/object><packing><property name=\"left-attach\">0</property><property n"
  "ame=\"top-attach\">0</property><property name=\"width\">2</property></p"
  "acking></child></object></child><child type=\"label\"><object class=\"G"
  "tkLabel\"><property name=\"visible\">True</property><property name=\"ca"
  "n-focus\">False</property><property name=\"margin-bottom\">6</property>"
  "<property name=\"label\" translatable=\"yes\">Calendar</property><attri"
  "butes><attribute name=\"weight\" value=\"bold\"/></attributes></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child><child><object class=\"GtkFrame\" id=\"frame3\">"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "False</property><property name=\"margin-bottom\">18</property><property"
  " name=\"label-xalign\">0</property><property name=\"shadow-type\">none<"
  "/property><child><object class=\"GtkGrid\"><property name=\"visible\">T"
  "rue</property><property name=\"can-focus\">False</property><property na"
  "me=\"margin-left\">18</property><property name=\"row-spacing\">6</prope"
  "rty><property name=\"column-spacing\">12</property><child><object class"
  "=\"GtkEntry\" id=\"tooltip-format\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">True</property><property name=\"hex"
  "pand\">True</property><property name=\"secondary-icon-name\">help-conte"
  "nts</property><property name=\"primary-icon-activatable\">False</proper"
  "ty><property name=\"secondary-icon-tooltip-text\" translatable=\"yes\">"
  "The format describes the date and time parts to insert into the panel. "
  "For example, %Y will be substituted with the year, %m with the month an"
  "d %d with the day. Similarly, &lt;b&gt;&lt;/b&gt; tags will make the te"
  "xt bold. See the \"Help\" page for additional information.</property></"
  "object><packing><property name=\"left-attach\">0</property><property na"
  "me=\"top-attach\">2</property><property name=\"width\">2</property></pa"
  "cking></child><child><object class=\"GtkComboBox\" id=\"tooltip-chooser"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"hexpand\">False</property><child><o"
  "bject class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attribut"
  "es><attribute name=\"text\">2</attribute></attributes></child></object>"
  "<packing><property name=\"left-attach\">1</property><property name=\"to"
  "p-attach\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label4\"><property name=\"visible\">True</property><property n"
  "ame=\"can-focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">_Tooltip format:</property><property name=\"use-underline\">Tr"
  "ue</property><property name=\"xalign\">0</property></object><packing><p"
  "roperty name=\"left-attach\">0</property><property name=\"top-attach\">"
  "1</property></packing></child><child><object class=\"GtkLabel\" id=\"la"
  "bel2\"><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">_L"
  "ayout:</property><property name=\"use-underline\">True</property><prope"
  "rty name=\"xalign\">0</property></object><packing><property name=\"left"
  "-attach\">0</property><property name=\"top-attach\">0</property></packi"
  "ng></child><child><object class=\"GtkComboBox\" id=\"mode\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">False</prop"
  "erty><property name=\"hexpand\">True</property><property name=\"model\""
  ">mode-model</property><child><object class=\"GtkCellRendererText\" id=\""
  "cellrenderertext1\"/><attributes><attribute name=\"text\">0</attribute>"
  "</attributes></child></object><packing><property name=\"left-attach\">1"
  "</property><property name=\"top-attach\">0</property></packing></child>"
  "</object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label1\"><property name=\"visible\">True</property><property name=\"can"
  "-focus\">False</property><property name=\"margin-bottom\">6</property><"
  "property name=\"label\" translatable=\"yes\">Appearance</property><attr"
  "ibutes><attribute name=\"weight\" value=\"bold\"/></attributes></object"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">2</pro"
  "perty></packing></child><child><object class=\"GtkFrame\" id=\"frame1\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"label-xalign\">0</property><property "
  "name=\"shadow-type\">none</property><child><object class=\"GtkGrid\"><p"
  "roperty name=\"visible\">True</property><property name=\"can-focus\">Fa"
  "lse</property><property name=\"margin-left\">18</property><property nam"
  "e=\"hexpand\">True</property><property name=\"row-spacing\">6</property"
  "><property name=\"column-spacing\">12</property><child><object class=\""
  "GtkCheckButton\" id=\"show-meridiem\"><property name=\"label\" translat"
  "able=\"yes\">Sho_w AM/PM</property><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">True</property><property name=\"rece"
  "ives-default\">False</property><property name=\"use-underline\">True</p"
  "roperty><property name=\"draw-indicator\">True</property></object><pack"
  "ing><property name=\"left-attach\">0</property><property name=\"top-att"
  "ach\">4</property><property name=\"width\">2</property></packing></chil"
  "d><child><object class=\"GtkCheckButton\" id=\"flash-separators\"><prop"
  "erty name=\"label\" translatable=\"yes\">Fl_ash time separators</proper"
  "ty><property name=\"visible\">True</property><property name=\"can-focus"
  "\">True</property><property name=\"receives-default\">False</property><"
  "property name=\"use-underline\">True</property><property name=\"draw-in"
  "dicator\">True</property></object><packing><property name=\"left-attach"
  "\">0</property><property name=\"top-attach\">3</property><property name"
  "=\"width\">2</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"show-military\"><property name=\"label\" translatable=\""
  "yes\">24-_hour clock</property><property name=\"visible\">True</propert"
  "y><property name=\"can-focus\">True</property><property name=\"receives"
  "-default\">False</property><property name=\"use-underline\">True</prope"
  "rty><property name=\"draw-indicator\">True</property></object><packing>"
  "<property name=\"left-attach\">0</property><property name=\"top-attach\""
  ">2</property><property name=\"width\">2</property></packing></child><ch"
  "ild><object class=\"GtkGrid\" id=\"binary-box\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"hexpand\">True</property><property name=\"row-spacing\">6</pr"
  "operty><property name=\"column-spacing\">12</property><child><object cl"
  "ass=\"GtkComboBox\" id=\"binary-mode\"><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">False</property><property name=\""
  "hexpand\">True</property><property name=\"model\">binary-mode-model</pr"
  "operty><child><object class=\"GtkCellRendererText\"/><attributes><attri"
  "bute name=\"text\">0</attribute></attributes></child></object><packing>"
  "<property name=\"left-attach\">1</property><property name=\"top-attach\""
  ">0</property></packing></child><child><object class=\"GtkLabel\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">Binary mode:</p"
  "roperty></object><packing><property name=\"left-attach\">0</property><p"
  "roperty name=\"top-attach\">0</property></packing></child></object><pac"
  "king><property name=\"left-attach\">0</property><property name=\"top-at"
  "tach\">0</property><property name=\"width\">2</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"show-seconds\"><propert"
  "y name=\"label\" translatable=\"yes\">Display _seconds</property><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">True</"
  "property><property name=\"receives-default\">False</property><property "
  "name=\"use-underline\">True</property><property name=\"draw-indicator\""
  ">True</property></object><packing><property name=\"left-attach\">0</pro"
  "perty><property name=\"top-attach\">1</property><property name=\"width\""
  ">2</property></packing></child><child><object class=\"GtkBox\" id=\"fuz"
  "ziness-box\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><child><object class=\"GtkLabel\" id=\"labe"
  "l5\"><property name=\"visible\">True</property><property name=\"can-foc"
  "us\">False</property><property name=\"label\" translatable=\"yes\" comm"
  "ents=\"I18N: the fuzziness the *precision* of the fuzzy clock. Time ste"
  "ps of 5, 15 or parts of the day.\">F_uzziness:</property><property name"
  "=\"use-underline\">True</property><property name=\"xalign\">0</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkScale\" id=\"hscale1\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">True</"
  "property><property name=\"hexpand\">True</property><property name=\"adj"
  "ustment\">fuzziness</property><property name=\"digits\">0</property><pr"
  "operty name=\"value-pos\">right</property></object><packing><property n"
  "ame=\"expand\">True</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child></object><packi"
  "ng><property name=\"left-attach\">0</property><property name=\"top-atta"
  "ch\">6</property><property name=\"width\">2</property></packing></child"
  "><child><object class=\"GtkCheckButton\" id=\"show-inactive\"><property"
  " name=\"label\" translatable=\"yes\">Show _inactive segments</property>"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "True</property><property name=\"receives-default\">False</property><pro"
  "perty name=\"use-underline\">True</property><property name=\"draw-indic"
  "ator\">True</property></object><packing><property name=\"left-attach\">"
  "0</property><property name=\"top-attach\">7</property><property name=\""
  "width\">2</property></packing></child><child><object class=\"GtkCheckBu"
  "tton\" id=\"show-grid\"><property name=\"label\" translatable=\"yes\">S"
  "how gri_d</property><property name=\"visible\">True</property><property"
  " name=\"can-focus\">True</property><property name=\"receives-default\">"
  "False</property><property name=\"use-underline\">True</property><proper"
  "ty name=\"draw-indicator\">True</property></object><packing><property n"
  "ame=\"left-attach\">0</property><property name=\"top-attach\">8</proper"
  "ty><property name=\"width\">2</property></packing></child><child><objec"
  "t class=\"GtkGrid\" id=\"digital-box\"><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">False</property><property name=\""
  "hexpand\">True</property><property name=\"row-spacing\">6</property><pr"
  "operty name=\"column-spacing\">12</property><child><object class=\"GtkL"
  "abel\" id=\"label8\"><property name=\"visible\">True</property><propert"
  "y name=\"can-focus\">False</property><property name=\"label\" translata"
  "ble=\"yes\">_Layout:</property><property name=\"use-underline\">True</p"
  "roperty><property name=\"xalign\">0</property></object><packing><proper"
  "ty name=\"left-attach\">0</property><property name=\"top-attach\">0</pr"
  "operty></packing></child><child><object class=\"GtkGrid\" id=\"digital-"
  "date\"><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"row-spacing\">6</property><prop"
  "erty name=\"column-spacing\">12</property><child><object class=\"GtkLab"
  "el\"><property name=\"visible\">True</property><property name=\"can-foc"
  "us\">False</property><property name=\"margin-left\">18</property><prope"
  "rty name=\"label\" translatable=\"yes\">Font:</property><property name="
  "\"xalign\">0.10000000149011612</property></object><packing><property na"
  "me=\"left-attach\">0</property><property name=\"top-attach\">1</propert"
  "y></packing></child><child><object class=\"GtkLabel\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"margin-left\">18</property><property name=\"label\" tra"
  "nslatable=\"yes\">Format:</property><property name=\"xalign\">0.1000000"
  "0149011612</property></object><packing><property name=\"left-attach\">0"
  "</property><property name=\"top-attach\">2</property></packing></child>"
  "<child><object class=\"GtkEntry\" id=\"digital-date-format\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">True</prop"
  "erty><property name=\"margin-left\">18</property><property name=\"hexpa"
  "nd\">True</property><property name=\"secondary-icon-name\">help-content"
  "s</property><property name=\"primary-icon-activatable\">False</property"
  "><property name=\"secondary-icon-tooltip-text\" translatable=\"yes\">Th"
  "e format describes the date and time parts to insert into the panel. Fo"
  "r example, %Y will be substituted with the year, %m with the month and "
  "%d with the day. Similarly, &lt;b&gt;&lt;/b&gt; tags will make the text"
  " bold. See the \"Help\" page for additional information.</property><pro"
  "perty name=\"secondary-icon-tooltip-markup\" translatable=\"yes\">The f"
  "ormat describes the date and time parts to insert into the panel. For e"
  "xample, %Y will be substituted with the year, %m with the month and %d "
  "with the day. Similarly, &amp;lt;b&amp;gt;&amp;lt;/b&amp;gt; tags will "
  "make the text bold. See the &amp;quot;Help&amp;quot; page for additiona"
  "l information.</property></object><packing><property name=\"left-attach"
  "\">0</property><property name=\"top-attach\">3</property><property name"
  "=\"width\">2</property></packing></child><child><object class=\"GtkComb"
  "oBox\" id=\"digital-date-chooser\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"hex"
  "pand\">True</property><child><object class=\"GtkCellRendererText\" id=\""
  "cellrenderertext4\"/><attributes><attribute name=\"text\">2</attribute>"
  "</attributes></child></object><packing><property name=\"left-attach\">1"
  "</property><property name=\"top-attach\">2</property></packing></child>"
  "<child><object class=\"GtkLabel\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">Date</property><property name=\"use-underline\""
  ">True</property><property name=\"xalign\">0</property><attributes><attr"
  "ibute name=\"weight\" value=\"bold\"/></attributes></object><packing><p"
  "roperty name=\"left-attach\">0</property><property name=\"top-attach\">"
  "0</property><property name=\"width\">3</property></packing></child><chi"
  "ld><object class=\"GtkFontButton\" id=\"digital-date-font\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">True</prope"
  "rty><property name=\"receives-default\">True</property><property name=\""
  "font\">Sans 12</property><property name=\"language\">en-in</property><p"
  "roperty name=\"preview-text\"/></object><packing><property name=\"left-"
  "attach\">1</property><property name=\"top-attach\">1</property></packin"
  "g></child></object><packing><property name=\"left-attach\">0</property>"
  "<property name=\"top-attach\">1</property><property name=\"width\">2</p"
  "roperty></packing></child><child><object class=\"GtkGrid\" id=\"digital"
  "-time\"><property name=\"visible\">True</property><property name=\"can-"
  "focus\">False</property><property name=\"row-spacing\">6</property><pro"
  "perty name=\"column-spacing\">12</property><child><object class=\"GtkLa"
  "bel\"><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">False</property><property name=\"label\" translatable=\"yes\">Tim"
  "e</property><property name=\"use-underline\">True</property><property n"
  "ame=\"xalign\">0</property><attributes><attribute name=\"weight\" value"
  "=\"bold\"/></attributes></object><packing><property name=\"left-attach\""
  ">0</property><property name=\"top-attach\">0</property><property name=\""
  "width\">3</property></packing></child><child><object class=\"GtkLabel\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"margin-left\">18</property><property "
  "name=\"label\" translatable=\"yes\">Font:</property><property name=\"xa"
  "lign\">0.10000000149011612</property></object><packing><property name=\""
  "left-attach\">0</property><property name=\"top-attach\">1</property></p"
  "acking></child><child><object class=\"GtkLabel\"><property name=\"visib"
  "le\">True</property><property name=\"can-focus\">False</property><prope"
  "rty name=\"margin-left\">18</property><property name=\"label\" translat"
  "able=\"yes\">Format:</property><property name=\"xalign\">0.100000001490"
  "11612</property></object><packing><property name=\"left-attach\">0</pro"
  "perty><property name=\"top-attach\">2</property></packing></child><chil"
  "d><object class=\"GtkEntry\" id=\"digital-time-format\"><property name="
  "\"visible\">True</property><property name=\"can-focus\">True</property>"
  "<property name=\"margin-left\">18</property><property name=\"hexpand\">"
  "True</property><property name=\"secondary-icon-name\">help-contents</pr"
  "operty><property name=\"primary-icon-activatable\">False</property><pro"
  "perty name=\"secondary-icon-tooltip-text\" translatable=\"yes\">The for"
  "mat describes the date and time parts to insert into the panel. For exa"
  "mple, %Y will be substituted with the year, %m with the month and %d wi"
  "th the day. Similarly, &lt;b&gt;&lt;/b&gt; tags will make the text bold"
  ". See the \"Help\" page for additional information.</property><property"
  " name=\"secondary-icon-tooltip-markup\" translatable=\"yes\">The format"
  " describes the date and time parts to insert into the panel. For exampl"
  "e, %Y will be substituted with the year, %m with the month and %d with "
  "the day. Similarly, &amp;lt;b&amp;gt;&amp;lt;/b&amp;gt; tags will make "
  "the text bold. See the &amp;quot;Help&amp;quot; page for additional inf"
  "ormation.</property></object><packing><property name=\"left-attach\">0<"
  "/property><property name=\"top-attach\">3</property><property name=\"wi"
  "dth\">2</property></packing></child><child><object class=\"GtkComboBox\""
  " id=\"digital-time-chooser\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"hexpand\""
  ">True</property><child><object class=\"GtkCellRendererText\" id=\"cellr"
  "enderertext5\"/><attributes><attribute name=\"text\">2</attribute></att"
  "ributes></child></object><packing><property name=\"left-attach\">1</pro"
  "perty><property name=\"top-attach\">2</property></packing></child><chil"
  "d><object class=\"GtkFontButton\" id=\"digital-time-font\"><property na"
  "me=\"visible\">True</property><property name=\"can-focus\">True</proper"
  "ty><property name=\"receives-default\">True</property><property name=\""
  "font\">Sans 12</property><property name=\"language\">en-in</property><p"
  "roperty name=\"preview-text\"/></object><packing><property name=\"left-"
  "attach\">1</property><property name=\"top-attach\">1</property></packin"
  "g></child></object><packing><property name=\"left-attach\">0</property>"
  "<property name=\"top-attach\">2</property><property name=\"width\">2</p"
  "roperty></packing></child><child><object class=\"GtkComboBox\" id=\"dig"
  "ital-layout\"><property name=\"visible\">True</property><property name="
  "\"can-focus\">False</property><property name=\"hexpand\">True</property"
  "><property name=\"model\">digital-format-model</property><property name"
  "=\"active\">0</property><child><object class=\"GtkCellRendererText\" id"
  "=\"cellrenderertext3\"/><attributes><attribute name=\"text\">0</attribu"
  "te></attributes></child></object><packing><property name=\"left-attach\""
  ">1</property><property name=\"top-attach\">0</property></packing></chil"
  "d></object><packing><property name=\"left-attach\">0</property><propert"
  "y name=\"top-attach\">5</property><property name=\"width\">2</property>"
  "</packing></child></object></child><child type=\"label\"><object class="
  "\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"margin-bott"
  "om\">6</property><property name=\"label\" translatable=\"yes\">Clock Op"
  "tions</property><attributes><attribute name=\"weight\" value=\"bold\"/>"
  "</attributes></object></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">3</property></packing></child></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child></object></c"
  "hild><action-widgets><action-widget response=\"0\">close-button</action"
  "-widget><action-widget response=\"0\">help-button</action-widget></acti"
  "on-widgets></object></interface>"
};

static const unsigned clock_dialog_ui_length = 28044u;

