/* automatically generated from color-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (color_dialog_ui)
#endif
#ifdef __GNUC__
static const char color_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char color_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.13\"/"
  "><object class=\"GtkListStore\" id=\"devices\"/><object class=\"GtkImag"
  "e\" id=\"image1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">list-add"
  "-symbolic</property><property name=\"use_fallback\">True</property></ob"
  "ject><object class=\"GtkImage\" id=\"image2\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"icon_name\">list-remove-symbolic</property><property name=\"use_"
  "fallback\">True</property></object><object class=\"GtkImage\" id=\"imag"
  "e3\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"icon_name\">folder-open-symbolic<"
  "/property></object><object class=\"GtkImage\" id=\"image4\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"icon_name\">dialog-information-symbolic</property"
  "></object><object class=\"GtkImage\" id=\"image5\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"icon_name\">dialog-information-symbolic</property></object"
  "><object class=\"GtkImage\" id=\"image6\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"icon_name\">help-browser</property></object><object class=\"GtkImag"
  "e\" id=\"image7\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">window-c"
  "lose-symbolic</property></object><object class=\"XfceTitledDialog\" id="
  "\"dialog\"><property name=\"can_focus\">False</property><property name="
  "\"title\" translatable=\"yes\">Color Profiles</property><property name="
  "\"window_position\">center-on-parent</property><property name=\"default"
  "_width\">700</property><property name=\"default_height\">400</property>"
  "<property name=\"icon_name\">org.xfce.settings.color</property><propert"
  "y name=\"type_hint\">dialog</property><child internal-child=\"vbox\"><o"
  "bject class=\"GtkBox\" id=\"dialog-vbox1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"orientation\">vertical</property><property name=\"spacing\">2</pro"
  "perty><child internal-child=\"action_area\"><object class=\"GtkButtonBo"
  "x\" id=\"dialog-action_area1\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"layout_"
  "style\">end</property><child><object class=\"GtkButton\" id=\"button2\""
  "><property name=\"label\" translatable=\"yes\">_Close</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">True</property><property na"
  "me=\"image\">image7</property><property name=\"use_underline\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkButton\" id=\"button1\""
  "><property name=\"label\" translatable=\"yes\">_Help</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">True</property><property nam"
  "e=\"image\">image6</property><property name=\"use_underline\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty><property name=\"secondary\">True</property></packing></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"pack_type\">end</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkBox\" id=\"plug-child\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"vexpand"
  "\">True</property><property name=\"orientation\">vertical</property><ch"
  "ild><object class=\"GtkPaned\" id=\"paned\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"margin_left\">6</property><property name=\"margin_right\">6</prope"
  "rty><property name=\"margin_top\">6</property><property name=\"margin_b"
  "ottom\">6</property><child><object class=\"GtkBox\" id=\"device\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"orientation\">vertical</property><child><ob"
  "ject class=\"GtkScrolledWindow\" id=\"scrolled-devices\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"hexpand\">True</property><property name=\"min_content"
  "_width\">250</property><child><placeholder/></child></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkBox\" id=\"label-no-devices\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"orientation\">vertical</property><child><object class=\"Gt"
  "kLabel\" id=\"label-no-devices-label\"><property name=\"visible\">True<"
  "/property><property name=\"sensitive\">False</property><property name=\""
  "can_focus\">False</property><property name=\"margin_left\">12</property"
  "><property name=\"margin_right\">12</property><property name=\"margin_t"
  "op\">12</property><property name=\"margin_bottom\">12</property><proper"
  "ty name=\"label\" translatable=\"yes\">&lt;b&gt;No devices found.&lt;/b"
  "&gt;</property><property name=\"use_markup\">True</property><property n"
  "ame=\"justify\">center</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><style><class name=\"vi"
  "ew\"/><class name=\"frame\"/></style></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">1</property></packing></child></object><packing><p"
  "roperty name=\"resize\">False</property><property name=\"shrink\">False"
  "</property></packing></child><child><object class=\"GtkBox\" id=\"profi"
  "le\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"margin_left\">24</property><prope"
  "rty name=\"margin_right\">24</property><property name=\"margin_top\">18"
  "</property><property name=\"margin_bottom\">24</property><property name"
  "=\"orientation\">vertical</property><child><object class=\"GtkGrid\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"margin_top\">6</property><property name="
  "\"margin_bottom\">18</property><property name=\"row_spacing\">3</proper"
  "ty><property name=\"column_spacing\">12</property><child><object class="
  "\"GtkLabel\" id=\"model\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"xalign\">0</"
  "property></object><packing><property name=\"left_attach\">2</property><"
  "property name=\"top_attach\">0</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"colorspace\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"xalign\">0</property></object><packing><property name=\"left_attach\""
  ">2</property><property name=\"top_attach\">2</property></packing></chil"
  "d><child><object class=\"GtkLabel\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">Model:</property><property name=\"xalign\">1"
  "</property></object><packing><property name=\"left_attach\">1</property"
  "><property name=\"top_attach\">0</property></packing></child><child><ob"
  "ject class=\"GtkLabel\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">Colorspace:</property><property name=\"xalign\">1</prope"
  "rty></object><packing><property name=\"left_attach\">1</property><prope"
  "rty name=\"top_attach\">2</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"vendor\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"xalign\""
  ">0</property></object><packing><property name=\"left_attach\">2</proper"
  "ty><property name=\"top_attach\">1</property></packing></child><child><"
  "object class=\"GtkLabel\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">Vendor:</property><property name=\"xalign\">1</propert"
  "y></object><packing><property name=\"left_attach\">1</property><propert"
  "y name=\"top_attach\">1</property></packing></child><child><object clas"
  "s=\"GtkImage\" id=\"device-icon\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"marg"
  "in_right\">12</property><property name=\"pixel_size\">64</property><pro"
  "perty name=\"icon_size\">3</property></object><packing><property name=\""
  "left_attach\">0</property><property name=\"top_attach\">0</property><pr"
  "operty name=\"height\">3</property></packing></child><child><object cla"
  "ss=\"GtkButton\" id=\"device-calibrate\"><property name=\"label\" trans"
  "latable=\"yes\">Calibrate</property><property name=\"visible\">False</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"halign\">start</proper"
  "ty><property name=\"margin_top\">6</property></object><packing><propert"
  "y name=\"left_attach\">1</property><property name=\"top_attach\">3</pro"
  "perty></packing></child><child><placeholder/></child><child><placeholde"
  "r/></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkScrolledWindow\" id"
  "=\"scrolled-profiles\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"vexpand\">True</"
  "property><property name=\"shadow_type\">in</property><child><placeholde"
  "r/></child></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child><child><object class=\"GtkBox\" id=\"label-no-"
  "profiles\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"hexpand\">True</property><p"
  "roperty name=\"orientation\">vertical</property><child><object class=\""
  "GtkLabel\" id=\"label-no-profiles-label\"><property name=\"visible\">Tr"
  "ue</property><property name=\"sensitive\">False</property><property nam"
  "e=\"can_focus\">False</property><property name=\"margin_left\">11</prop"
  "erty><property name=\"margin_right\">11</property><property name=\"marg"
  "in_top\">11</property><property name=\"margin_bottom\">11</property><pr"
  "operty name=\"vexpand\">True</property><property name=\"label\" transla"
  "table=\"yes\">&lt;b&gt;No profiles for the selected device.&lt;/b&gt;</"
  "property><property name=\"use_markup\">True</property><property name=\""
  "justify\">center</property></object><packing><property name=\"expand\">"
  "True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><style><class name=\"view\"/><"
  "class name=\"frame\"/></style></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">2</property></packing></child><child><object class=\"Gtk"
  "Frame\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class=\"GtkBo"
  "x\" id=\"profiles-toolbar\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><child><object class=\"GtkB"
  "ox\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><child><object class=\"GtkButton\" id=\"profiles-a"
  "dd\"><property name=\"label\" translatable=\"yes\">_Add</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">True</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">Add a profile to the current"
  "ly selected device</property><property name=\"image\">image1</property>"
  "<property name=\"use_underline\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkButton\" id=\"profiles-remove\"><property name=\"labe"
  "l\" translatable=\"yes\">_Remove</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">True</property><property name=\"tooltip_text\" t"
  "ranslatable=\"yes\">Delete the currently selected profile</property><pr"
  "operty name=\"image\">image2</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkButton\" id=\""
  "profiles-info\"><property name=\"visible\">False</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Tru"
  "e</property><property name=\"tooltip_text\" translatable=\"yes\">Show d"
  "etailed information about the selected profile</property><property name"
  "=\"image\">image4</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">2</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkBox\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"orientation\">verti"
  "cal</property><child><object class=\"GtkButton\" id=\"profiles-enable\""
  "><property name=\"label\" translatable=\"yes\">Enable</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">True</property><property na"
  "me=\"tooltip_text\" translatable=\"yes\">Enable the selected profile</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pac"
  "k_type\">end</property><property name=\"position\">2</property></packin"
  "g></child></object></child><child type=\"label_item\"><placeholder/></c"
  "hild><style><class name=\"inline-toolbar\"/></style></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">True</"
  "property><property name=\"position\">3</property></packing></child></ob"
  "ject><packing><property name=\"resize\">True</property><property name=\""
  "shrink\">False</property></packing></child><style><class name=\"frame\""
  "/></style></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object></child><action-widgets>"
  "<action-widget response=\"0\">button2</action-widget><action-widget res"
  "ponse=\"-11\">button1</action-widget></action-widgets></object><object "
  "class=\"GtkListStore\" id=\"liststore-assign\"><columns><column type=\""
  "gchararray\"/><column type=\"GObject\"/><column type=\"guint\"/><column"
  " type=\"gchararray\"/></columns></object><object class=\"XfceTitledDial"
  "og\" id=\"dialog-assign\"><property name=\"can_focus\">False</property>"
  "<property name=\"title\" translatable=\"yes\">Add Profile to Device</pr"
  "operty><property name=\"modal\">True</property><property name=\"default"
  "_width\">350</property><property name=\"default_height\">500</property>"
  "<property name=\"icon_name\">xfce4-color-settings</property><property n"
  "ame=\"type_hint\">dialog</property><property name=\"transient_for\">dia"
  "log</property><child internal-child=\"vbox\"><object class=\"GtkBox\"><"
  "property name=\"can_focus\">False</property><property name=\"orientatio"
  "n\">vertical</property><property name=\"spacing\">2</property><child in"
  "ternal-child=\"action_area\"><object class=\"GtkButtonBox\"><property n"
  "ame=\"can_focus\">False</property><property name=\"layout_style\">end</"
  "property><child><object class=\"GtkButton\" id=\"assign-cancel\"><prope"
  "rty name=\"label\" translatable=\"yes\">_Cancel</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">True</property><property name=\"u"
  "se_underline\">True</property></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkB"
  "utton\" id=\"assign-ok\"><property name=\"label\" translatable=\"yes\">"
  "_OK</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">True</"
  "property><property name=\"use_underline\">True</property></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">1</property></packing></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkBox\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"margin_left\">12</property><property name=\"margin_right\">12"
  "</property><property name=\"margin_top\">12</property><property name=\""
  "orientation\">vertical</property><child><object class=\"GtkScrolledWind"
  "ow\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"shadow_type\">in</property><child>"
  "<object class=\"GtkTreeView\" id=\"treeview-assign\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"model\">liststore-assign</property><child internal-child="
  "\"selection\"><object class=\"GtkTreeSelection\"/></child></object></ch"
  "ild></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkBox\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"margin_bottom\">12</property><child><object class=\"GtkButt"
  "on\" id=\"assign-import\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">True</property><property name=\"tooltip_text\" translatable=\"yes"
  "\">Import color profile files (*.icc)</property><property name=\"halign"
  "\">start</property><property name=\"image\">image3</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkButton\" id=\"assign-info\"><property n"
  "ame=\"visible\">False</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><property name="
  "\"tooltip_text\" translatable=\"yes\">Show detailed information about t"
  "he selected profile</property><property name=\"image\">image5</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child><style><class name=\"inline-toolbar\"/></style></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child></object></child></object><object class=\"GtkListS"
  "tore\" id=\"profiles\"/></interface>"
};

static const unsigned color_dialog_ui_length = 19404u;

