/* automatically generated from applicationsmenu-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (applicationsmenu_dialog_ui)
#endif
#ifdef __GNUC__
static const char applicationsmenu_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char applicationsmenu_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.24\"/><requires lib=\"libxfce4ui-2\" version=\"4.17\"/"
  "><object class=\"GtkImage\" id=\"image1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can-focus\">False</property><property nam"
  "e=\"icon-name\">alacarte</property></object><object class=\"GtkImage\" "
  "id=\"image2\"><property name=\"visible\">True</property><property name="
  "\"can-focus\">False</property><property name=\"icon-name\">help-browser"
  "</property></object><object class=\"GtkImage\" id=\"image3\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"icon-name\">window-close-symbolic</property></ob"
  "ject><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\""
  "can-focus\">False</property><property name=\"title\" translatable=\"yes"
  "\">Applications Menu</property><property name=\"icon-name\">org.xfce.pa"
  "nel.applicationsmenu</property><property name=\"type-hint\">normal</pro"
  "perty><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dial"
  "og-vbox2\"><property name=\"visible\">True</property><property name=\"c"
  "an-focus\">False</property><property name=\"orientation\">vertical</pro"
  "perty><property name=\"spacing\">2</property><child internal-child=\"ac"
  "tion_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area2\"><"
  "property name=\"visible\">True</property><property name=\"can-focus\">F"
  "alse</property><property name=\"layout-style\">end</property><child><ob"
  "ject class=\"GtkButton\" id=\"help-button\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Help</property><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">True</property><property name=\"rece"
  "ives-default\">True</property><property name=\"image\">image2</property"
  "><property name=\"use-underline\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">0</property><property name=\"seconda"
  "ry\">True</property></packing></child><child><object class=\"GtkButton\""
  " id=\"close-button\"><property name=\"label\" translatable=\"yes\">_Clo"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can-focus\">True</property><property name=\"receives-default\">True</pr"
  "operty><property name=\"image\">image3</property><property name=\"use-u"
  "nderline\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"pack-type\">end</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkBox\" id=\"vbox1"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"border-width\">6</property><propert"
  "y name=\"orientation\">vertical</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkFrame\" id=\"frame3\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">False</proper"
  "ty><property name=\"label-xalign\">0</property><property name=\"shadow-"
  "type\">none</property><child><object class=\"GtkGrid\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"margin-left\">18</property><property name=\"row-spacing"
  "\">6</property><property name=\"column-spacing\">12</property><child><o"
  "bject class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">False</property><property name=\""
  "label\" translatable=\"yes\">_Icon:</property><property name=\"use-unde"
  "rline\">True</property><property name=\"xalign\">0</property></object><"
  "packing><property name=\"left-attach\">0</property><property name=\"top"
  "-attach\">6</property></packing></child><child><object class=\"GtkEntry"
  "\" id=\"button-title\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">True</property><property name=\"invisible-char\""
  ">\342\200\242</property></object><packing><property name=\"left-attach\""
  ">1</property><property name=\"top-attach\">5</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label2\"><property name=\"visi"
  "ble\">True</property><property name=\"can-focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">Button _title:</property><prop"
  "erty name=\"use-underline\">True</property><property name=\"xalign\">0<"
  "/property></object><packing><property name=\"left-attach\">0</property>"
  "<property name=\"top-attach\">5</property></packing></child><child><obj"
  "ect class=\"GtkCheckButton\" id=\"small\"><property name=\"label\" tran"
  "slatable=\"yes\">Show button on one _line</property><property name=\"vi"
  "sible\">True</property><property name=\"can-focus\">True</property><pro"
  "perty name=\"receives-default\">False</property><property name=\"use-un"
  "derline\">True</property><property name=\"draw-indicator\">True</proper"
  "ty></object><packing><property name=\"left-attach\">0</property><proper"
  "ty name=\"top-attach\">4</property><property name=\"width\">2</property"
  "></packing></child><child><object class=\"GtkCheckButton\" id=\"show-bu"
  "tton-title\"><property name=\"label\" translatable=\"yes\">_Show button"
  " title</property><property name=\"visible\">True</property><property na"
  "me=\"can-focus\">True</property><property name=\"receives-default\">Fal"
  "se</property><property name=\"use-underline\">True</property><property "
  "name=\"draw-indicator\">True</property></object><packing><property name"
  "=\"left-attach\">0</property><property name=\"top-attach\">3</property>"
  "<property name=\"width\">2</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"show-tooltips\"><property name=\"label\" t"
  "ranslatable=\"yes\">Show application d_escription in tooltip</property>"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "True</property><property name=\"receives-default\">False</property><pro"
  "perty name=\"use-underline\">True</property><property name=\"image-posi"
  "tion\">right</property><property name=\"draw-indicator\">True</property"
  "></object><packing><property name=\"left-attach\">0</property><property"
  " name=\"top-attach\">2</property><property name=\"width\">2</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"show-menu"
  "-icons\"><property name=\"label\" translatable=\"yes\">Show ic_ons in m"
  "enu</property><property name=\"visible\">True</property><property name="
  "\"can-focus\">True</property><property name=\"receives-default\">False<"
  "/property><property name=\"use-underline\">True</property><property nam"
  "e=\"draw-indicator\">True</property></object><packing><property name=\""
  "left-attach\">0</property><property name=\"top-attach\">1</property><pr"
  "operty name=\"width\">2</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"show-generic-names\"><property name=\"label\""
  " translatable=\"yes\">Show generic application n_ames</property><proper"
  "ty name=\"visible\">True</property><property name=\"can-focus\">True</p"
  "roperty><property name=\"receives-default\">False</property><property n"
  "ame=\"tooltip-text\" translatable=\"yes\">Select this option to show th"
  "e generic application name in the menu, for example \"File Manager\" in"
  "stead of \"Thunar\"</property><property name=\"use-underline\">True</pr"
  "operty><property name=\"draw-indicator\">True</property></object><packi"
  "ng><property name=\"left-attach\">0</property><property name=\"top-atta"
  "ch\">0</property><property name=\"width\">2</property></packing></child"
  "><child><object class=\"GtkButton\" id=\"icon-button\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">True</property><p"
  "roperty name=\"receives-default\">True</property><property name=\"halig"
  "n\">start</property></object><packing><property name=\"left-attach\">1<"
  "/property><property name=\"top-attach\">6</property></packing></child><"
  "/object></child><child type=\"label\"><object class=\"GtkLabel\" id=\"l"
  "abel1\"><property name=\"visible\">True</property><property name=\"can-"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">A"
  "ppearance</property><attributes><attribute name=\"weight\" value=\"bold"
  "\"/></attributes></object></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkFrame\" id=\"frame1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">False</property><property name=\"label-xalign\""
  ">0</property><property name=\"shadow-type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\">"
  "True</property><property name=\"can-focus\">False</property><property n"
  "ame=\"left-padding\">12</property><child><object class=\"GtkBox\" id=\""
  "vbox2\"><property name=\"visible\">True</property><property name=\"can-"
  "focus\">False</property><property name=\"border-width\">6</property><pr"
  "operty name=\"orientation\">vertical</property><property name=\"spacing"
  "\">6</property><child><object class=\"GtkBox\" id=\"hbox1\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">False</prop"
  "erty><property name=\"spacing\">12</property><child><object class=\"Gtk"
  "RadioButton\" id=\"use-default-menu\"><property name=\"label\" translat"
  "able=\"yes\">Use the _default menu</property><property name=\"visible\""
  ">True</property><property name=\"can-focus\">True</property><property n"
  "ame=\"receives-default\">False</property><property name=\"use-underline"
  "\">True</property><property name=\"draw-indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">0</property></packi"
  "ng></child><child><object class=\"GtkButton\" id=\"edit-menu-button\"><"
  "property name=\"label\" translatable=\"yes\">Ed_it Menu</property><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">True<"
  "/property><property name=\"receives-default\">True</property><property "
  "name=\"image\">image1</property><property name=\"use-underline\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkRadioB"
  "utton\" id=\"use-custom-menu\"><property name=\"label\" translatable=\""
  "yes\">Use c_ustom menu file:</property><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">True</property><property name=\""
  "receives-default\">False</property><property name=\"use-underline\">Tru"
  "e</property><property name=\"active\">True</property><property name=\"d"
  "raw-indicator\">True</property><property name=\"group\">use-default-men"
  "u</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child><child><object class=\"GtkAlignment\" id=\"a"
  "lignment5\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><property name=\"left-padding\">22</propert"
  "y><child><object class=\"GtkHBox\" id=\"custom-box\"><property name=\"v"
  "isible\">True</property><property name=\"can-focus\">False</property><p"
  "roperty name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label5\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Menu _file:</property><property name=\"use-underline\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkFileChooserButton\" id=\""
  "custom-file\"><property name=\"visible\">True</property><property name="
  "\"can-focus\">False</property><property name=\"title\" translatable=\"y"
  "es\">Select A Menu File</property></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">1</property></packing></child></object></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">Menu File</property><attributes><attribute na"
  "me=\"weight\" value=\"bold\"/></attributes></object></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object></child><action-widgets><action-widget respo"
  "nse=\"0\">help-button</action-widget><action-widget response=\"0\">clos"
  "e-button</action-widget></action-widgets></object><object class=\"GtkSi"
  "zeGroup\" id=\"sizegroup1\"/></interface>"
};

static const unsigned applicationsmenu_dialog_ui_length = 12616u;

