/* automatically generated from pager-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (pager_dialog_ui)
#endif
#ifdef __GNUC__
static const char pager_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char pager_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.24\"/><requires lib=\"libxfce4ui-2\" version=\"4.17\"/"
  "><object class=\"GtkListStore\" id=\"appearance-model\"><columns><colum"
  "n type=\"gchararray\"/><column type=\"gint\"/></columns><data><row><col"
  " id=\"0\" translatable=\"yes\">Buttons</col><col id=\"1\">0</col></row>"
  "<row><col id=\"0\" translatable=\"yes\">Miniature View</col><col id=\"1"
  "\">1</col></row></data></object><object class=\"GtkImage\" id=\"image1\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"icon-name\">org.xfce.workspaces</prop"
  "erty></object><object class=\"GtkImage\" id=\"image2\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"icon-name\">help-browser</property></object><object cla"
  "ss=\"GtkImage\" id=\"image3\"><property name=\"visible\">True</property"
  "><property name=\"can-focus\">False</property><property name=\"icon-nam"
  "e\">window-close-symbolic</property></object><object class=\"GtkAdjustm"
  "ent\" id=\"rows\"><property name=\"lower\">1</property><property name=\""
  "upper\">10</property><property name=\"value\">1</property><property nam"
  "e=\"step-increment\">1</property><property name=\"page-increment\">10</"
  "property></object><object class=\"XfceTitledDialog\" id=\"dialog\"><pro"
  "perty name=\"can-focus\">False</property><property name=\"title\" trans"
  "latable=\"yes\">Workspace Switcher</property><property name=\"icon-name"
  "\">org.xfce.panel.pager</property><property name=\"type-hint\">normal</"
  "property><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"d"
  "ialog-vbox2\"><property name=\"visible\">True</property><property name="
  "\"can-focus\">False</property><property name=\"orientation\">vertical</"
  "property><property name=\"spacing\">2</property><child internal-child=\""
  "action_area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area2\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"layout-style\">end</property><child t"
  "ype=\"center\"><object class=\"GtkButton\" id=\"settings-button\"><prop"
  "erty name=\"label\" translatable=\"yes\">Workspace _Settings...</proper"
  "ty><property name=\"visible\">True</property><property name=\"can-focus"
  "\">True</property><property name=\"receives-default\">True</property><p"
  "roperty name=\"halign\">start</property><property name=\"image\">image1"
  "</property><property name=\"use-underline\">True</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property><property name="
  "\"secondary\">True</property></packing></child><child><object class=\"G"
  "tkButton\" id=\"help-button\"><property name=\"label\" translatable=\"y"
  "es\">_Help</property><property name=\"visible\">True</property><propert"
  "y name=\"can-focus\">True</property><property name=\"receives-default\""
  ">True</property><property name=\"image\">image2</property><property nam"
  "e=\"use-underline\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">0</property><property name=\"secondary\">True</pro"
  "perty></packing></child><child><object class=\"GtkButton\" id=\"close-b"
  "utton\"><property name=\"label\" translatable=\"yes\">_Close</property>"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "True</property><property name=\"receives-default\">True</property><prop"
  "erty name=\"image\">image3</property><property name=\"use-underline\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "2</property></packing></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"pack-type\">end</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkGrid\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"border-width\">6</property><property name=\"row-spacing\">"
  "6</property><property name=\"column-spacing\">12</property><child><obje"
  "ct class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">False</property><property name=\"ma"
  "rgin-left\">12</property><property name=\"label\" translatable=\"yes\">"
  "Number of _rows:</property><property name=\"use-underline\">True</prope"
  "rty><property name=\"xalign\">0</property></object><packing><property n"
  "ame=\"left-attach\">0</property><property name=\"top-attach\">1</proper"
  "ty></packing></child><child><object class=\"GtkSpinButton\" id=\"spin1\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">True</property><property name=\"halign\">end</property><property name="
  "\"adjustment\">rows</property><property name=\"snap-to-ticks\">True</pr"
  "operty><property name=\"numeric\">True</property><property name=\"updat"
  "e-policy\">if-valid</property></object><packing><property name=\"left-a"
  "ttach\">1</property><property name=\"top-attach\">1</property></packing"
  "></child><child><object class=\"GtkSwitch\" id=\"numbering\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">True</prop"
  "erty><property name=\"halign\">end</property><property name=\"valign\">"
  "center</property></object><packing><property name=\"left-attach\">1</pr"
  "operty><property name=\"top-attach\">2</property></packing></child><chi"
  "ld><object class=\"GtkSwitch\" id=\"workspace-scrolling\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">True</propert"
  "y><property name=\"halign\">end</property><property name=\"valign\">cen"
  "ter</property></object><packing><property name=\"left-attach\">1</prope"
  "rty><property name=\"top-attach\">3</property></packing></child><child>"
  "<object class=\"GtkSwitch\" id=\"wrap-workspaces\"><property name=\"vis"
  "ible\">True</property><property name=\"sensitive\" bind-source=\"worksp"
  "ace-scrolling\" bind-property=\"active\" bind-flags=\"sync-create\">Fal"
  "se</property><property name=\"can-focus\">True</property><property name"
  "=\"halign\">end</property><property name=\"valign\">center</property></"
  "object><packing><property name=\"left-attach\">1</property><property na"
  "me=\"top-attach\">4</property></packing></child><child><object class=\""
  "GtkLabel\" id=\"numbering-label\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"marg"
  "in-left\">12</property><property name=\"label\" translatable=\"yes\">Sh"
  "ow workspace number</property><property name=\"xalign\">0</property></o"
  "bject><packing><property name=\"left-attach\">0</property><property nam"
  "e=\"top-attach\">2</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"workspace-scrolling-label\"><property name=\"visible\">T"
  "rue</property><property name=\"can-focus\">False</property><property na"
  "me=\"margin-left\">12</property><property name=\"label\" translatable=\""
  "yes\">Switch workspaces using the mouse wheel</property><property name="
  "\"xalign\">0</property></object><packing><property name=\"left-attach\""
  ">0</property><property name=\"top-attach\">3</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"wrap-workspaces-label\"><prope"
  "rty name=\"visible\">True</property><property name=\"sensitive\" bind-s"
  "ource=\"workspace-scrolling\" bind-property=\"active\" bind-flags=\"syn"
  "c-create\">False</property><property name=\"can-focus\">False</property"
  "><property name=\"margin-left\">12</property><property name=\"label\" t"
  "ranslatable=\"yes\">Wrap around workspaces</property><property name=\"x"
  "align\">0</property></object><packing><property name=\"left-attach\">0<"
  "/property><property name=\"top-attach\">4</property></packing></child><"
  "child><object class=\"GtkBox\"><property name=\"visible\">True</propert"
  "y><property name=\"can-focus\">False</property><property name=\"spacing"
  "\">12</property><child><object class=\"GtkLabel\" id=\"label5\"><proper"
  "ty name=\"visible\">True</property><property name=\"can-focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Appeara"
  "nce&lt;/b&gt;</property><property name=\"use-markup\">True</property><p"
  "roperty name=\"xalign\">0</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkComboBox\" id=\"appearance\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"hal"
  "ign\">end</property><property name=\"hexpand\">True</property><property"
  " name=\"model\">appearance-model</property><property name=\"active\">0<"
  "/property><property name=\"id-column\">1</property><child><object class"
  "=\"GtkCellRendererText\" id=\"renderer\"/><attributes><attribute name=\""
  "text\">0</attribute></attributes></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child></object><packi"
  "ng><property name=\"left-attach\">0</property><property name=\"top-atta"
  "ch\">0</property><property name=\"width\">2</property></packing></child"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">1</property></p"
  "acking></child></object></child><action-widgets><action-widget response"
  "=\"0\">help-button</action-widget><action-widget response=\"0\">close-b"
  "utton</action-widget></action-widgets></object></interface>"
};

static const unsigned pager_dialog_ui_length = 9049u;

