/* automatically generated from panel-preferences-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (panel_preferences_dialog_ui)
#endif
#ifdef __GNUC__
static const char panel_preferences_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char panel_preferences_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.24\"/><requires lib=\"libxfce4ui-2\" version=\"4.17\"/"
  "><object class=\"GtkListStore\" id=\"autohide-behavior-store\"><columns"
  "><column type=\"gchararray\"/></columns><data><row><col id=\"0\" transl"
  "atable=\"yes\">Never</col></row><row><col id=\"0\" translatable=\"yes\""
  ">Intelligently</col></row><row><col id=\"0\" translatable=\"yes\">Alway"
  "s</col></row></data></object><object class=\"GtkSizeGroup\" id=\"bg-siz"
  "egroup\"/><object class=\"GtkSizeGroup\" id=\"display-sizegroup\"/><obj"
  "ect class=\"GtkAdjustment\" id=\"enter-opacity\"><property name=\"upper"
  "\">100</property><property name=\"value\">100</property><property name="
  "\"step-increment\">1</property><property name=\"page-increment\">10</pr"
  "operty></object><object class=\"GtkAdjustment\" id=\"icon-size\"><prope"
  "rty name=\"upper\">100</property><property name=\"step-increment\">1</p"
  "roperty><property name=\"page-increment\">10</property></object><object"
  " class=\"GtkImage\" id=\"image10\"><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">False</property><property name=\"ico"
  "n-name\">package-x-generic</property></object><object class=\"GtkImage\""
  " id=\"image11\"><property name=\"visible\">True</property><property nam"
  "e=\"can-focus\">False</property><property name=\"icon-name\">window-clo"
  "se-symbolic</property></object><object class=\"GtkImage\" id=\"image12\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"icon-name\">help-browser</property></"
  "object><object class=\"GtkImage\" id=\"image5\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"icon-name\">list-add-symbolic</property></object><object clas"
  "s=\"GtkImage\" id=\"image6\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"icon-name"
  "\">list-remove-symbolic</property></object><object class=\"GtkAdjustmen"
  "t\" id=\"leave-opacity\"><property name=\"upper\">100</property><proper"
  "ty name=\"value\">100</property><property name=\"step-increment\">1</pr"
  "operty><property name=\"page-increment\">10</property></object><object "
  "class=\"GtkAdjustment\" id=\"length\"><property name=\"lower\">1</prope"
  "rty><property name=\"upper\">1</property><property name=\"value\">1</pr"
  "operty><property name=\"step-increment\">1</property><property name=\"p"
  "age-increment\">100</property></object><object class=\"GtkListStore\" i"
  "d=\"mode-store\"><columns><column type=\"gchararray\"/></columns><data>"
  "<row><col id=\"0\" translatable=\"yes\">Horizontal</col></row><row><col"
  " id=\"0\" translatable=\"yes\">Vertical</col></row><row><col id=\"0\" t"
  "ranslatable=\"yes\">Deskbar</col></row></data></object><object class=\""
  "GtkAdjustment\" id=\"nrows\"><property name=\"lower\">1</property><prop"
  "erty name=\"upper\">6</property><property name=\"value\">1</property><p"
  "roperty name=\"step-increment\">1</property><property name=\"page-incre"
  "ment\">1</property></object><object class=\"GtkListStore\" id=\"output-"
  "store\"><columns><column type=\"gchararray\"/><column type=\"gchararray"
  "\"/></columns></object><object class=\"GtkListStore\" id=\"panel-store\""
  "><columns><column type=\"gint\"/><column type=\"gchararray\"/></columns"
  "></object><object class=\"GtkAdjustment\" id=\"size\"><property name=\""
  "lower\">16</property><property name=\"upper\">128</property><property n"
  "ame=\"value\">16</property><property name=\"step-increment\">1</propert"
  "y><property name=\"page-increment\">10</property></object><object class"
  "=\"GtkAdjustment\" id=\"border-width\"><property name=\"upper\">128</pr"
  "operty><property name=\"value\">0</property><property name=\"step-incre"
  "ment\">1</property><property name=\"page-increment\">10</property></obj"
  "ect><object class=\"GtkListStore\" id=\"styles-store\"><columns><column"
  " type=\"gchararray\"/></columns><data><row><col id=\"0\" translatable=\""
  "yes\">None (use system style)</col></row><row><col id=\"0\" translatabl"
  "e=\"yes\">Solid color</col></row><row><col id=\"0\" translatable=\"yes\""
  ">Background image</col></row></data></object><object class=\"XfceTitled"
  "Dialog\" id=\"dialog\"><property name=\"can-focus\">False</property><pr"
  "operty name=\"title\" translatable=\"yes\">Panel Preferences</property>"
  "<property name=\"window-position\">center-on-parent</property><property"
  " name=\"icon-name\">org.xfce.panel</property><property name=\"type-hint"
  "\">normal</property><child internal-child=\"vbox\"><object class=\"GtkB"
  "ox\" id=\"dialog-vbox1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">2</property><child inter"
  "nal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialog-ac"
  "tion_area1\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><property name=\"layout-style\">end</proper"
  "ty><child><object class=\"GtkButton\" id=\"button-close\"><property nam"
  "e=\"label\" translatable=\"yes\">_Close</property><property name=\"visi"
  "ble\">True</property><property name=\"can-focus\">True</property><prope"
  "rty name=\"receives-default\">True</property><property name=\"image\">i"
  "mage11</property><property name=\"use-underline\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">0</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"button-help\"><proper"
  "ty name=\"label\" translatable=\"yes\">_Help</property><property name=\""
  "visible\">True</property><property name=\"can-focus\">True</property><p"
  "roperty name=\"receives-default\">True</property><property name=\"image"
  "\">image12</property><property name=\"use-underline\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">1</property><pro"
  "perty name=\"secondary\">True</property></packing></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"pack-type\">end</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kBox\" id=\"plug-child\"><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">False</property><property name=\"border-width\""
  ">6</property><property name=\"orientation\">vertical</property><propert"
  "y name=\"spacing\">12</property><child><object class=\"GtkGrid\" id=\"p"
  "anel-profiles\"><property name=\"visible\">True</property><property nam"
  "e=\"can-focus\">False</property><property name=\"row-spacing\">6</prope"
  "rty><property name=\"column-spacing\">12</property><child><object class"
  "=\"GtkBox\" id=\"hbox7\"><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">False</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkLabel\"><property name=\"visible\">T"
  "rue</property><property name=\"can-focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">Profiles:</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">0</property></packing></child></"
  "object><packing><property name=\"left-attach\">0</property><property na"
  "me=\"top-attach\">0</property></packing></child><child><object class=\""
  "GtkSeparator\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"hexpand\">True</propert"
  "y></object><packing><property name=\"left-attach\">0</property><propert"
  "y name=\"top-attach\">1</property><property name=\"width\">2</property>"
  "</packing></child><child><object class=\"GtkButton\" id=\"panel-switch\""
  "><property name=\"label\" translatable=\"yes\">_Backup and restore</pro"
  "perty><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">True</property><property name=\"receives-default\">True</property"
  "><property name=\"tooltip-text\" translatable=\"yes\">Switch between pa"
  "nel presets</property><property name=\"image\">image10</property><prope"
  "rty name=\"use-underline\">True</property></object><packing><property n"
  "ame=\"left-attach\">1</property><property name=\"top-attach\">0</proper"
  "ty></packing></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkBox\" id="
  "\"hbox3\"><property name=\"visible\">True</property><property name=\"ca"
  "n-focus\">False</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkComboBox\" id=\"panel-combobox\"><property name=\"v"
  "isible\">True</property><property name=\"can-focus\">False</property><p"
  "roperty name=\"model\">panel-store</property><child><object class=\"Gtk"
  "CellRendererText\" id=\"cellrenderertext2\"/><attributes><attribute nam"
  "e=\"text\">1</attribute></attributes></child></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkButton\" id=\"panel-add\"><property name=\"visible\">True"
  "</property><property name=\"can-focus\">True</property><property name=\""
  "receives-default\">True</property><property name=\"tooltip-text\" trans"
  "latable=\"yes\">Add a new panel</property><child><object class=\"GtkIma"
  "ge\" id=\"image1\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"margin-left\">3</pr"
  "operty><property name=\"margin-right\">3</property><property name=\"mar"
  "gin-top\">3</property><property name=\"margin-bottom\">3</property><pro"
  "perty name=\"icon-name\">list-add</property></object></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild><child><object class=\"GtkButton\" id=\"panel-remove\"><property n"
  "ame=\"visible\">True</property><property name=\"sensitive\">False</prop"
  "erty><property name=\"can-focus\">True</property><property name=\"recei"
  "ves-default\">True</property><property name=\"tooltip-text\" translatab"
  "le=\"yes\">Remove the currently selected panel</property><child><object"
  " class=\"GtkImage\" id=\"image2\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"marg"
  "in-left\">3</property><property name=\"margin-right\">3</property><prop"
  "erty name=\"margin-top\">3</property><property name=\"margin-bottom\">3"
  "</property><property name=\"icon-name\">list-remove</property></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">2</prop"
  "erty></packing></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child><child><object class=\"GtkNoteboo"
  "k\" id=\"notebook\"><property name=\"visible\">True</property><property"
  " name=\"sensitive\">False</property><property name=\"can-focus\">True</"
  "property><child><object class=\"GtkBox\" id=\"vbox2\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"border-width\">12</property><property name=\"orientatio"
  "n\">vertical</property><property name=\"spacing\">6</property><child><o"
  "bject class=\"GtkGrid\"><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><property name=\"margin-bottom\""
  ">18</property><property name=\"row-spacing\">6</property><property name"
  "=\"column-spacing\">12</property><child><object class=\"GtkLabel\" id=\""
  "label2\"><property name=\"visible\">True</property><property name=\"can"
  "-focus\">False</property><property name=\"hexpand\">True</property><pro"
  "perty name=\"label\" translatable=\"yes\">&lt;b&gt;General&lt;/b&gt;</p"
  "roperty><property name=\"use-markup\">True</property><property name=\"x"
  "align\">0</property></object><packing><property name=\"left-attach\">0<"
  "/property><property name=\"top-attach\">0</property><property name=\"wi"
  "dth\">2</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label1\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><property name=\"margin-left\">12</property"
  "><property name=\"label\" translatable=\"yes\">M_ode:</property><proper"
  "ty name=\"use-underline\">True</property><property name=\"xalign\">0</p"
  "roperty></object><packing><property name=\"left-attach\">0</property><p"
  "roperty name=\"top-attach\">1</property></packing></child><child><objec"
  "t class=\"GtkComboBox\" id=\"mode\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">False</property><property name=\"he"
  "xpand\">True</property><property name=\"model\">mode-store</property><c"
  "hild><object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><a"
  "ttributes><attribute name=\"text\">0</attribute></attributes></child></"
  "object><packing><property name=\"left-attach\">1</property><property na"
  "me=\"top-attach\">1</property></packing></child><child><object class=\""
  "GtkCheckButton\" id=\"span-monitors\"><property name=\"label\" translat"
  "able=\"yes\">Span mo_nitors</property><property name=\"visible\">True</"
  "property><property name=\"can-focus\">True</property><property name=\"r"
  "eceives-default\">False</property><property name=\"tooltip-text\" trans"
  "latable=\"yes\">Select this option to extend the panel over multiple mo"
  "nitors.</property><property name=\"margin-left\">12</property><property"
  " name=\"use-underline\">True</property><property name=\"draw-indicator\""
  ">True</property></object><packing><property name=\"left-attach\">0</pro"
  "perty><property name=\"top-attach\">3</property><property name=\"width\""
  ">2</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"position-locked\"><property name=\"label\" translatable=\"yes\">_L"
  "ock panel</property><property name=\"visible\">True</property><property"
  " name=\"can-focus\">True</property><property name=\"receives-default\">"
  "False</property><property name=\"tooltip-text\" translatable=\"yes\">Se"
  "lect this option to hide the handles of the panel and lock its position"
  ".</property><property name=\"margin-left\">12</property><property name="
  "\"use-underline\">True</property><property name=\"draw-indicator\">True"
  "</property></object><packing><property name=\"left-attach\">0</property"
  "><property name=\"top-attach\">4</property><property name=\"width\">2</"
  "property></packing></child><child><object class=\"GtkCheckButton\" id=\""
  "enable-struts\"><property name=\"label\" translatable=\"yes\">_Reserve "
  "space on screen edges for the panel</property><property name=\"visible\""
  ">True</property><property name=\"can-focus\">True</property><property n"
  "ame=\"receives-default\">False</property><property name=\"tooltip-text\""
  " translatable=\"yes\">Select this option if you don\'t want maximized w"
  "indows to cover the area behind the panel. This only works when the pan"
  "el is attached to a screen edge.</property><property name=\"margin-left"
  "\">12</property><property name=\"use-underline\">True</property><proper"
  "ty name=\"draw-indicator\">True</property></object><packing><property n"
  "ame=\"left-attach\">0</property><property name=\"top-attach\">6</proper"
  "ty><property name=\"width\">2</property></packing></child><child><objec"
  "t class=\"GtkBox\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"spacing\">12</prope"
  "rty><child><object class=\"GtkLabel\" id=\"autohide_label\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">False</prop"
  "erty><property name=\"margin-left\">12</property><property name=\"label"
  "\" translatable=\"yes\">Au_tomatically hide the panel:</property><prope"
  "rty name=\"use-underline\">True</property><property name=\"xalign\">0</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkComboBox\" id=\"autoh"
  "ide-behavior\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"model\">autohide-behavi"
  "or-store</property><child><object class=\"GtkCellRendererText\" id=\"ce"
  "llrenderertext5\"/><attributes><attribute name=\"text\">0</attribute></"
  "attributes></child></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"pack-typ"
  "e\">end</property><property name=\"position\">1</property></packing></c"
  "hild></object><packing><property name=\"left-attach\">0</property><prop"
  "erty name=\"top-attach\">5</property><property name=\"width\">2</proper"
  "ty></packing></child><child><object class=\"GtkLabel\" id=\"output-labe"
  "l\"><property name=\"visible\">True</property><property name=\"can-focu"
  "s\">False</property><property name=\"margin-left\">12</property><proper"
  "ty name=\"label\" translatable=\"yes\">O_utput:</property><property nam"
  "e=\"use-underline\">True</property><property name=\"xalign\">0</propert"
  "y></object><packing><property name=\"left-attach\">0</property><propert"
  "y name=\"top-attach\">2</property></packing></child><child><object clas"
  "s=\"GtkComboBox\" id=\"output-name\"><property name=\"visible\">True</p"
  "roperty><property name=\"can-focus\">False</property><property name=\"m"
  "odel\">output-store</property><child><object class=\"GtkCellRendererTex"
  "t\" id=\"cellrenderertext3\"/><attributes><attribute name=\"text\">1</a"
  "ttribute></attributes></child></object><packing><property name=\"left-a"
  "ttach\">1</property><property name=\"top-attach\">2</property></packing"
  "></child></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkGrid\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">False</propert"
  "y><property name=\"row-spacing\">6</property><property name=\"column-sp"
  "acing\">12</property><child><object class=\"GtkLabel\" id=\"label5\"><p"
  "roperty name=\"visible\">True</property><property name=\"can-focus\">Fa"
  "lse</property><property name=\"label\" translatable=\"yes\" comments=\""
  "I18N: name of the section (frame) in the panel preferences where the us"
  "er can define the length and size of the panel\">&lt;b&gt;Measurements&"
  "lt;/b&gt;</property><property name=\"use-markup\">True</property><prope"
  "rty name=\"xalign\">0</property></object><packing><property name=\"left"
  "-attach\">0</property><property name=\"top-attach\">0</property><proper"
  "ty name=\"width\">2</property></packing></child><child><object class=\""
  "GtkLabel\" id=\"label3\"><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">False</property><property name=\"margin-left\""
  ">12</property><property name=\"label\" translatable=\"yes\">Row _size ("
  "pixels):</property><property name=\"use-underline\">True</property><pro"
  "perty name=\"xalign\">0</property></object><packing><property name=\"le"
  "ft-attach\">0</property><property name=\"top-attach\">1</property></pac"
  "king></child><child><object class=\"GtkLabel\" id=\"label18\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">False</pr"
  "operty><property name=\"margin-left\">12</property><property name=\"lab"
  "el\" translatable=\"yes\">Num_ber of rows:</property><property name=\"u"
  "se-underline\">True</property><property name=\"xalign\">0</property></o"
  "bject><packing><property name=\"left-attach\">0</property><property nam"
  "e=\"top-attach\">2</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"label4\"><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><property name=\"margin-left\">"
  "12</property><property name=\"label\" translatable=\"yes\">L_ength (pix"
  "els):</property><property name=\"use-underline\">True</property><proper"
  "ty name=\"xalign\">0</property></object><packing><property name=\"left-"
  "attach\">0</property><property name=\"top-attach\">4</property></packin"
  "g></child><child><object class=\"GtkScale\" id=\"length-scale\"><proper"
  "ty name=\"visible\">True</property><property name=\"can-focus\">True</p"
  "roperty><property name=\"hexpand\">True</property><property name=\"adju"
  "stment\">length</property><property name=\"digits\">0</property><proper"
  "ty name=\"value-pos\">right</property></object><packing><property name="
  "\"left-attach\">1</property><property name=\"top-attach\">4</property><"
  "/packing></child><child><object class=\"GtkLabel\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"margin-left\">12</property><property name=\"hexpand\">True"
  "</property><property name=\"label\" translatable=\"yes\">Border width ("
  "pixels):</property><property name=\"xalign\">0</property></object><pack"
  "ing><property name=\"left-attach\">0</property><property name=\"top-att"
  "ach\">3</property></packing></child><child><object class=\"GtkSpinButto"
  "n\" id=\"border-width-spin-button\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">True</property><property name=\"hal"
  "ign\">end</property><property name=\"valign\">center</property><propert"
  "y name=\"adjustment\">border-width</property></object><packing><propert"
  "y name=\"left-attach\">1</property><property name=\"top-attach\">3</pro"
  "perty></packing></child><child><object class=\"GtkCheckButton\" id=\"le"
  "ngth-adjust\"><property name=\"label\" translatable=\"yes\">A_utomatica"
  "lly increase the length</property><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">True</property><property name=\"recei"
  "ves-default\">False</property><property name=\"tooltip-text\" translata"
  "ble=\"yes\">Select this option to automatically increase the length of "
  "the panel if the plugins request more space.</property><property name=\""
  "margin-left\">12</property><property name=\"use-underline\">True</prope"
  "rty><property name=\"draw-indicator\">True</property></object><packing>"
  "<property name=\"left-attach\">0</property><property name=\"top-attach\""
  ">5</property><property name=\"width\">2</property></packing></child><ch"
  "ild><object class=\"GtkSpinButton\" id=\"size-scale\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">True</property><p"
  "roperty name=\"halign\">end</property><property name=\"valign\">center<"
  "/property><property name=\"adjustment\">size</property></object><packin"
  "g><property name=\"left-attach\">1</property><property name=\"top-attac"
  "h\">1</property></packing></child><child><object class=\"GtkSpinButton\""
  " id=\"nrows-scale\"><property name=\"visible\">True</property><property"
  " name=\"can-focus\">True</property><property name=\"halign\">end</prope"
  "rty><property name=\"valign\">center</property><property name=\"adjustm"
  "ent\">nrows</property></object><packing><property name=\"left-attach\">"
  "1</property><property name=\"top-attach\">2</property></packing></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">2</property></"
  "packing></child></object></child><child type=\"tab\"><object class=\"Gt"
  "kLabel\" id=\"label6\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">D_isplay</property><property name=\"use-underline\">True<"
  "/property></object><packing><property name=\"tab-fill\">False</property"
  "></packing></child><child><object class=\"GtkBox\" id=\"vbox7\"><proper"
  "ty name=\"visible\">True</property><property name=\"can-focus\">False</"
  "property><property name=\"border-width\">12</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkGrid\" id=\"general-grid\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"margin-bottom\">18</property><property name=\"row-spaci"
  "ng\">6</property><property name=\"column-spacing\">12</property><child>"
  "<object class=\"GtkLabel\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">&lt;b&gt;General&lt;/b&gt;</property><property name=\""
  "use-markup\">True</property><property name=\"xalign\">0</property></obj"
  "ect><packing><property name=\"left-attach\">0</property><property name="
  "\"top-attach\">0</property></packing></child><child><object class=\"Gtk"
  "Label\"><property name=\"visible\">True</property><property name=\"can-"
  "focus\">False</property><property name=\"margin-left\">12</property><pr"
  "operty name=\"hexpand\">True</property><property name=\"label\" transla"
  "table=\"yes\">Dark mode</property><property name=\"xalign\">0</property"
  "></object><packing><property name=\"left-attach\">0</property><property"
  " name=\"top-attach\">1</property></packing></child><child><object class"
  "=\"GtkSwitch\" id=\"dark-mode\"><property name=\"visible\">True</proper"
  "ty><property name=\"can-focus\">True</property><property name=\"halign\""
  ">end</property><property name=\"valign\">center</property></object><pac"
  "king><property name=\"left-attach\">1</property><property name=\"top-at"
  "tach\">1</property></packing></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkGrid\" id=\"background-grid\"><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">False</property><property name=\"ma"
  "rgin-bottom\">18</property><property name=\"row-spacing\">6</property><"
  "property name=\"column-spacing\">12</property><child><object class=\"Gt"
  "kLabel\" id=\"label8\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"hexpand\">True<"
  "/property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Backgr"
  "ound&lt;/b&gt;</property><property name=\"use-markup\">True</property><"
  "property name=\"xalign\">0</property></object><packing><property name=\""
  "left-attach\">0</property><property name=\"top-attach\">0</property><pr"
  "operty name=\"width\">2</property></packing></child><child><object clas"
  "s=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"margin-le"
  "ft\">12</property><property name=\"label\" translatable=\"yes\">_Style:"
  "</property><property name=\"use-underline\">True</property><property na"
  "me=\"xalign\">0</property></object><packing><property name=\"left-attac"
  "h\">0</property><property name=\"top-attach\">1</property></packing></c"
  "hild><child><object class=\"GtkComboBox\" id=\"background-style\"><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">False"
  "</property><property name=\"hexpand\">True</property><property name=\"m"
  "odel\">styles-store</property><child><object class=\"GtkCellRendererTex"
  "t\" id=\"cellrenderertext4\"/><attributes><attribute name=\"text\">0</a"
  "ttribute></attributes></child></object><packing><property name=\"left-a"
  "ttach\">1</property><property name=\"top-attach\">1</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"background-rgba-label\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"margin-left\">12</property><property "
  "name=\"label\" translatable=\"yes\">C_olor:</property><property name=\""
  "use-underline\">True</property><property name=\"xalign\">0</property></"
  "object><packing><property name=\"left-attach\">0</property><property na"
  "me=\"top-attach\">2</property></packing></child><child><object class=\""
  "GtkColorButton\" id=\"background-rgba\"><property name=\"visible\">True"
  "</property><property name=\"can-focus\">False</property><property name="
  "\"receives-default\">True</property><property name=\"halign\">end</prop"
  "erty><property name=\"title\" translatable=\"yes\">Pick a Panel Color</"
  "property><property name=\"rgba\">rgb(217,64,217)</property></object><pa"
  "cking><property name=\"left-attach\">1</property><property name=\"top-a"
  "ttach\">2</property></packing></child><child><object class=\"GtkLabel\""
  " id=\"background-image-label\"><property name=\"visible\">True</propert"
  "y><property name=\"can-focus\">False</property><property name=\"margin-"
  "left\">12</property><property name=\"label\" translatable=\"yes\">_File"
  ":</property><property name=\"use-underline\">True</property><property n"
  "ame=\"xalign\">0</property></object><packing><property name=\"left-atta"
  "ch\">0</property><property name=\"top-attach\">3</property></packing></"
  "child><child><object class=\"GtkFileChooserButton\" id=\"background-ima"
  "ge\"><property name=\"visible\">True</property><property name=\"can-foc"
  "us\">False</property><property name=\"title\" translatable=\"yes\">Sele"
  "ct A Background Image</property></object><packing><property name=\"left"
  "-attach\">1</property><property name=\"top-attach\">3</property></packi"
  "ng></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">1</p"
  "roperty></packing></child><child><object class=\"GtkGrid\" id=\"icons-g"
  "rid\"><property name=\"name\">icons-grid</property><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"margin-bottom\">18</property><property name=\"row-spacing\""
  ">6</property><property name=\"column-spacing\">12</property><child><obj"
  "ect class=\"GtkLabel\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">&lt;b&gt;Icons&lt;/b&gt;</property><property name=\"use-m"
  "arkup\">True</property><property name=\"xalign\">0</property></object><"
  "packing><property name=\"left-attach\">0</property><property name=\"top"
  "-attach\">0</property></packing></child><child><object class=\"GtkLabel"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"margin-left\">12</property><propert"
  "y name=\"label\" translatable=\"yes\">Adjust size au_tomatically</prope"
  "rty><property name=\"use-underline\">True</property><property name=\"xa"
  "lign\">0</property></object><packing><property name=\"left-attach\">0</"
  "property><property name=\"top-attach\">1</property></packing></child><c"
  "hild><object class=\"GtkSwitch\" id=\"icon-size-switch\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">True</property"
  "><property name=\"halign\">end</property><property name=\"valign\">cent"
  "er</property></object><packing><property name=\"left-attach\">1</proper"
  "ty><property name=\"top-attach\">1</property></packing></child><child><"
  "object class=\"GtkRevealer\" id=\"icon-size-revealer\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"reveal-child\">True</property><child><object class=\"Gt"
  "kBox\"><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"hexpand\">True</property><prope"
  "rty name=\"spacing\">6</property><child><object class=\"GtkLabel\"><pro"
  "perty name=\"visible\">True</property><property name=\"can-focus\">Fals"
  "e</property><property name=\"margin-left\">12</property><property name="
  "\"label\" translatable=\"yes\">Fixed icon _size (pixels):</property><pr"
  "operty name=\"use-underline\">True</property><property name=\"xalign\">"
  "0</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkSpinButton\" id=\""
  "icon-size-spinbutton\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">True</property><property name=\"adjustment\">ico"
  "n-size</property></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"pack-type"
  "\">end</property><property name=\"position\">1</property></packing></ch"
  "ild></object></child></object><packing><property name=\"left-attach\">0"
  "</property><property name=\"top-attach\">2</property><property name=\"w"
  "idth\">2</property></packing></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">2</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"label11\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">&lt;b&gt;Opacity&lt;/b&gt;</property><property name"
  "=\"use-markup\">True</property><property name=\"xalign\">0</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">3</property></pac"
  "king></child><child><object class=\"GtkRevealer\" id=\"composited-info\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"reveal-child\">True</property><child>"
  "<object class=\"GtkInfoBar\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><child internal-child=\"ac"
  "tion_area\"><object class=\"GtkButtonBox\"><property name=\"can-focus\""
  ">False</property><property name=\"spacing\">6</property><property name="
  "\"layout-style\">end</property><child><object class=\"GtkButton\" id=\""
  "xfwm4-settings\"><property name=\"label\" translatable=\"yes\">Configur"
  "e...</property><property name=\"visible\">True</property><property name"
  "=\"can-focus\">True</property><property name=\"receives-default\">True<"
  "/property></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">0</property></packing></child><child internal-child=\"content"
  "_area\"><object class=\"GtkBox\"><property name=\"can-focus\">False</pr"
  "operty><property name=\"spacing\">6</property><child><object class=\"Gt"
  "kImage\"><property name=\"visible\">True</property><property name=\"can"
  "-focus\">False</property><property name=\"icon-name\">dialog-informatio"
  "n-symbolic</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label17\"><property name=\"visible\">True</property><property name="
  "\"can-focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">&lt;b&gt;Compositing is currently disabled&lt;/b&gt;\nEnable compo"
  "siting in the window manager for opacity settings in the panel.</proper"
  "ty><property name=\"use-markup\">True</property><property name=\"wrap\""
  ">True</property><property name=\"max-width-chars\">0</property></object"
  "><packing><property name=\"expand\">True</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty></packing></child></object></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">4</property></packing></child><child><object cl"
  "ass=\"GtkGrid\" id=\"composited\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"marg"
  "in-left\">12</property><property name=\"row-spacing\">6</property><prop"
  "erty name=\"column-spacing\">12</property><child><object class=\"GtkLab"
  "el\" id=\"label9\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\" comments=\"I18N: label for the enter transparency slider\">_E"
  "nter:</property><property name=\"use-underline\">True</property><proper"
  "ty name=\"xalign\">0</property></object><packing><property name=\"left-"
  "attach\">0</property><property name=\"top-attach\">0</property></packin"
  "g></child><child><object class=\"GtkScale\" id=\"enter-opacity-scale\">"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "True</property><property name=\"hexpand\">True</property><property name"
  "=\"adjustment\">enter-opacity</property><property name=\"digits\">0</pr"
  "operty><property name=\"value-pos\">right</property></object><packing><"
  "property name=\"left-attach\">1</property><property name=\"top-attach\""
  ">0</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel10\"><property name=\"visible\">True</property><property name=\"can"
  "-focus\">False</property><property name=\"label\" translatable=\"yes\" "
  "comments=\"I18N: label for the leave transparency slider\">_Leave:</pro"
  "perty><property name=\"use-underline\">True</property><property name=\""
  "xalign\">0</property></object><packing><property name=\"left-attach\">0"
  "</property><property name=\"top-attach\">1</property></packing></child>"
  "<child><object class=\"GtkScale\" id=\"leave-opacity-scale\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">True</prop"
  "erty><property name=\"tooltip-text\" translatable=\"yes\">Transparency "
  "when the pointer is not hovering over the panel, with 0 being fully tra"
  "nsparent and 100 fully opaque.</property><property name=\"hexpand\">Tru"
  "e</property><property name=\"adjustment\">leave-opacity</property><prop"
  "erty name=\"digits\">0</property><property name=\"value-pos\">right</pr"
  "operty></object><packing><property name=\"left-attach\">1</property><pr"
  "operty name=\"top-attach\">1</property></packing></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">5</property></packing></child"
  "></object><packing><property name=\"position\">1</property></packing></"
  "child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label12\"><pr"
  "operty name=\"visible\">True</property><property name=\"can-focus\">Fal"
  "se</property><property name=\"label\" translatable=\"yes\">Appeara_nce<"
  "/property><property name=\"use-underline\">True</property></object><pac"
  "king><property name=\"position\">1</property><property name=\"tab-fill\""
  ">False</property></packing></child><child><object class=\"GtkBox\" id=\""
  "hbox4\"><property name=\"visible\">True</property><property name=\"can-"
  "focus\">False</property><property name=\"border-width\">12</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkBox\"><p"
  "roperty name=\"visible\">True</property><property name=\"can-focus\">Fa"
  "lse</property><property name=\"orientation\">vertical</property><child>"
  "<object class=\"GtkScrolledWindow\" id=\"scrolledwindow3\"><property na"
  "me=\"visible\">True</property><property name=\"can-focus\">True</proper"
  "ty><property name=\"shadow-type\">etched-in</property><child><object cl"
  "ass=\"GtkTreeView\" id=\"item-treeview\"><property name=\"visible\">Tru"
  "e</property><property name=\"can-focus\">True</property><property name="
  "\"vexpand\">True</property><property name=\"headers-visible\">False</pr"
  "operty><property name=\"rules-hint\">True</property><property name=\"en"
  "able-search\">False</property><child internal-child=\"selection\"><obje"
  "ct class=\"GtkTreeSelection\"/></child></object></child></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkBox\" id=\"vbox6\"><property name=\"visible\">"
  "True</property><property name=\"can-focus\">False</property><child><obj"
  "ect class=\"GtkButton\" id=\"item-add\"><property name=\"label\" transl"
  "atable=\"yes\">_Add</property><property name=\"visible\">True</property"
  "><property name=\"sensitive\">False</property><property name=\"can-focu"
  "s\">True</property><property name=\"receives-default\">True</property><"
  "property name=\"tooltip-text\" translatable=\"yes\">Add new item to thi"
  "s panel</property><property name=\"image\">image5</property><property n"
  "ame=\"use-underline\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">2</property></packing></child><child><object class"
  "=\"GtkButton\" id=\"item-remove\"><property name=\"label\" translatable"
  "=\"yes\">_Remove</property><property name=\"visible\">True</property><p"
  "roperty name=\"sensitive\">False</property><property name=\"can-focus\""
  ">True</property><property name=\"receives-default\">True</property><pro"
  "perty name=\"tooltip-text\" translatable=\"yes\">Remove currently selec"
  "ted item</property><property name=\"image\">image6</property><property "
  "name=\"use-underline\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">3</property></packing></child><child><object cla"
  "ss=\"GtkButton\" id=\"item-properties\"><property name=\"visible\">True"
  "</property><property name=\"sensitive\">False</property><property name="
  "\"can-focus\">True</property><property name=\"receives-default\">True</"
  "property><property name=\"tooltip-text\" translatable=\"yes\">Edit the "
  "currently selected item</property><child><object class=\"GtkImage\" id="
  "\"image7\"><property name=\"visible\">True</property><property name=\"c"
  "an-focus\">False</property><property name=\"icon-name\">document-proper"
  "ties-symbolic</property></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">4</property></packing></child><child><object "
  "class=\"GtkButton\" id=\"item-about\"><property name=\"visible\">True</"
  "property><property name=\"sensitive\">False</property><property name=\""
  "can-focus\">True</property><property name=\"receives-default\">True</pr"
  "operty><property name=\"tooltip-text\" translatable=\"yes\">Show about "
  "information of the currently selected item</property><child><object cla"
  "ss=\"GtkImage\" id=\"image8\"><property name=\"visible\">True</property"
  "><property name=\"can-focus\">False</property><property name=\"icon-nam"
  "e\">help-about-symbolic</property></object></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">5</property></packing></child><styl"
  "e><class name=\"inline-toolbar\"/></style></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">2</property></packing></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkBox\"><property name=\"visible\">True</proper"
  "ty><property name=\"can-focus\">False</property><property name=\"orient"
  "ation\">vertical</property><child><object class=\"GtkButton\" id=\"item"
  "-up\"><property name=\"visible\">True</property><property name=\"sensit"
  "ive\">False</property><property name=\"can-focus\">True</property><prop"
  "erty name=\"receives-default\">True</property><property name=\"tooltip-"
  "text\" translatable=\"yes\">Move currently selected item up by one row<"
  "/property><child><object class=\"GtkImage\" id=\"image3\"><property nam"
  "e=\"visible\">True</property><property name=\"can-focus\">False</proper"
  "ty><property name=\"icon-name\">go-up-symbolic</property></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkButton\" id=\"item-down\"><"
  "property name=\"visible\">True</property><property name=\"sensitive\">F"
  "alse</property><property name=\"can-focus\">True</property><property na"
  "me=\"receives-default\">True</property><property name=\"tooltip-text\" "
  "translatable=\"yes\">Move currently selected item down by one row</prop"
  "erty><child><object class=\"GtkImage\" id=\"image4\"><property name=\"v"
  "isible\">True</property><property name=\"can-focus\">False</property><p"
  "roperty name=\"icon-name\">go-down-symbolic</property></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">1</property></p"
  "acking></child><style><class name=\"linked\"/></style></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">2</property></packing></child></"
  "object><packing><property name=\"position\">2</property></packing></chi"
  "ld><child type=\"tab\"><object class=\"GtkLabel\" id=\"label14\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">Ite_ms</propert"
  "y><property name=\"use-underline\">True</property></object><packing><pr"
  "operty name=\"position\">2</property><property name=\"tab-fill\">False<"
  "/property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">2</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child></object></ch"
  "ild><action-widgets><action-widget response=\"0\">button-close</action-"
  "widget><action-widget response=\"1\">button-help</action-widget></actio"
  "n-widgets></object></interface>"
};

static const unsigned panel_preferences_dialog_ui_length = 42782u;

