/* automatically generated from display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (display_dialog_ui)
#endif
#ifdef __GNUC__
static const char display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.13\"/"
  "><object class=\"GtkAdjustment\" id=\"adjustment1\"><property name=\"lo"
  "wer\">0.10</property><property name=\"upper\">10</property><property na"
  "me=\"step-increment\">0.25</property><property name=\"page-increment\">"
  "1</property></object><object class=\"GtkImage\" id=\"image1\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">False</pr"
  "operty><property name=\"icon-name\">edit-delete-symbolic</property></ob"
  "ject><object class=\"GtkImage\" id=\"image2\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"icon-name\">document-save-symbolic</property></object><object cl"
  "ass=\"GtkImage\" id=\"image3\"><property name=\"visible\">True</propert"
  "y><property name=\"can-focus\">False</property><property name=\"icon-na"
  "me\">window-close-symbolic</property></object><object class=\"GtkImage\""
  " id=\"image4\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"icon-name\">object-sele"
  "ct-symbolic</property></object><object class=\"GtkImage\" id=\"image5\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"icon-name\">document-new-symbolic</pr"
  "operty></object><object class=\"GtkImage\" id=\"image6\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">False</propert"
  "y><property name=\"icon-name\">help-browser</property></object><object "
  "class=\"GtkImage\" id=\"image7\"><property name=\"visible\">True</prope"
  "rty><property name=\"can-focus\">False</property><property name=\"icon-"
  "name\">object-select-symbolic</property></object><object class=\"GtkIma"
  "ge\" id=\"image8\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"icon-name\">dialog-"
  "information</property></object><object class=\"GtkListStore\" id=\"list"
  "store1\"><columns><column type=\"gchararray\"/><column type=\"guint\"/>"
  "</columns><data><row><col id=\"0\" translatable=\"yes\">Never</col><col"
  " id=\"1\">0</col></row><row><col id=\"0\" translatable=\"yes\">When a d"
  "isplay is connected</col><col id=\"1\">1</col></row><row><col id=\"0\" "
  "translatable=\"yes\">When a display is disconnected</col><col id=\"1\">"
  "2</col></row><row><col id=\"0\" translatable=\"yes\">Always</col><col i"
  "d=\"1\">3</col></row></data></object><object class=\"GtkListStore\" id="
  "\"liststore2\"><columns><column type=\"gchararray\"/><column type=\"gui"
  "nt\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Do nothin"
  "g</col><col id=\"1\">0</col></row><row><col id=\"0\" translatable=\"yes"
  "\">Show dialog</col><col id=\"1\">1</col></row><row><col id=\"0\" trans"
  "latable=\"yes\">Mirror</col><col id=\"1\">2</col></row><row><col id=\"0"
  "\" translatable=\"yes\">Extend</col><col id=\"1\">3</col></row></data><"
  "/object><object class=\"GtkPopover\" id=\"primary-info\"><property name"
  "=\"can-focus\">False</property><property name=\"position\">bottom</prop"
  "erty><child><object class=\"GtkGrid\"><property name=\"visible\">True</"
  "property><property name=\"can-focus\">False</property><property name=\""
  "margin-left\">12</property><property name=\"margin-right\">12</property"
  "><property name=\"margin-top\">12</property><property name=\"margin-bot"
  "tom\">12</property><child><object class=\"GtkImage\" id=\"panel-ok\"><p"
  "roperty name=\"can-focus\">False</property><property name=\"margin-left"
  "\">18</property><property name=\"icon-name\">emblem-ok-symbolic</proper"
  "ty><style><class name=\"success\"/></style></object><packing><property "
  "name=\"left-attach\">0</property><property name=\"top-attach\">1</prope"
  "rty></packing></child><child><object class=\"GtkImage\" id=\"desktop-ok"
  "\"><property name=\"can-focus\">False</property><property name=\"margin"
  "-left\">18</property><property name=\"icon-name\">emblem-ok-symbolic</p"
  "roperty></object><packing><property name=\"left-attach\">0</property><p"
  "roperty name=\"top-attach\">2</property></packing></child><child><objec"
  "t class=\"GtkImage\" id=\"notifications-ok\"><property name=\"can-focus"
  "\">False</property><property name=\"margin-left\">18</property><propert"
  "y name=\"icon-name\">emblem-ok-symbolic</property></object><packing><pr"
  "operty name=\"left-attach\">0</property><property name=\"top-attach\">3"
  "</property></packing></child><child><object class=\"GtkLabel\"><propert"
  "y name=\"visible\">True</property><property name=\"can-focus\">False</p"
  "roperty><property name=\"margin-bottom\">12</property><property name=\""
  "label\" translatable=\"yes\">The primary display can be configured to s"
  "how:</property><property name=\"xalign\">0</property></object><packing>"
  "<property name=\"left-attach\">0</property><property name=\"top-attach\""
  ">0</property><property name=\"width\">3</property></packing></child><ch"
  "ild><object class=\"GtkLabel\" id=\"panel-label\"><property name=\"visi"
  "ble\">True</property><property name=\"can-focus\">False</property><prop"
  "erty name=\"hexpand\">True</property><property name=\"label\" translata"
  "ble=\"yes\">Xfce Panel</property><property name=\"xalign\">0</property>"
  "</object><packing><property name=\"left-attach\">1</property><property "
  "name=\"top-attach\">1</property></packing></child><child><object class="
  "\"GtkLabel\" id=\"desktop-label\"><property name=\"visible\">True</prop"
  "erty><property name=\"can-focus\">False</property><property name=\"hexp"
  "and\">True</property><property name=\"label\" translatable=\"yes\">Desk"
  "top icons</property><property name=\"xalign\">0</property></object><pac"
  "king><property name=\"left-attach\">1</property><property name=\"top-at"
  "tach\">2</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"notifications-label\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"hexpand\">T"
  "rue</property><property name=\"label\" translatable=\"yes\">Notificatio"
  "ns</property><property name=\"xalign\">0</property></object><packing><p"
  "roperty name=\"left-attach\">1</property><property name=\"top-attach\">"
  "3</property></packing></child><child><object class=\"GtkButton\" id=\"p"
  "anel-configure\"><property name=\"label\" translatable=\"yes\">Configur"
  "e...</property><property name=\"visible\">True</property><property name"
  "=\"can-focus\">True</property><property name=\"receives-default\">True<"
  "/property><style><class name=\"flat\"/></style></object><packing><prope"
  "rty name=\"left-attach\">2</property><property name=\"top-attach\">1</p"
  "roperty></packing></child><child><object class=\"GtkButton\" id=\"deskt"
  "op-configure\"><property name=\"label\" translatable=\"yes\">Configure."
  "..</property><property name=\"visible\">True</property><property name=\""
  "can-focus\">True</property><property name=\"receives-default\">True</pr"
  "operty><style><class name=\"flat\"/></style></object><packing><property"
  " name=\"left-attach\">2</property><property name=\"top-attach\">2</prop"
  "erty></packing></child><child><object class=\"GtkButton\" id=\"notifica"
  "tions-configure\"><property name=\"label\" translatable=\"yes\">Configu"
  "re...</property><property name=\"visible\">True</property><property nam"
  "e=\"can-focus\">True</property><property name=\"receives-default\">True"
  "</property><style><class name=\"flat\"/></style></object><packing><prop"
  "erty name=\"left-attach\">2</property><property name=\"top-attach\">3</"
  "property></packing></child></object></child></object><object class=\"Xf"
  "ceTitledDialog\" id=\"display-dialog\"><property name=\"can-focus\">Fal"
  "se</property><property name=\"title\" translatable=\"yes\">Display</pro"
  "perty><property name=\"window-position\">center-on-parent</property><pr"
  "operty name=\"default-width\">400</property><property name=\"default-he"
  "ight\">400</property><property name=\"icon-name\">org.xfce.settings.dis"
  "play</property><property name=\"type-hint\">dialog</property><child int"
  "ernal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox1\"><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">False"
  "</property><property name=\"orientation\">vertical</property><property "
  "name=\"spacing\">2</property><child internal-child=\"action_area\"><obj"
  "ect class=\"GtkButtonBox\" id=\"dialog-action_area1\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">False</property><"
  "property name=\"layout-style\">end</property><child><object class=\"Gtk"
  "Button\" id=\"button-help\"><property name=\"label\" translatable=\"yes"
  "\">_Help</property><property name=\"visible\">True</property><property "
  "name=\"can-focus\">True</property><property name=\"receives-default\">T"
  "rue</property><property name=\"image\">image6</property><property name="
  "\"use-underline\">True</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">0</property><property name=\"secondary\">True</prope"
  "rty></packing></child><child><object class=\"GtkButton\" id=\"button-cl"
  "ose\"><property name=\"label\" translatable=\"yes\">_Close</property><p"
  "roperty name=\"visible\">True</property><property name=\"can-focus\">Tr"
  "ue</property><property name=\"receives-default\">True</property><proper"
  "ty name=\"image\">image3</property><property name=\"use-underline\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">1<"
  "/property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"pack-type\">end</property><property name=\"position\">1</property></p"
  "acking></child><child><object class=\"GtkBox\" id=\"plug-child\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property><property name=\"border-width\">6</property><property name=\""
  "orientation\">vertical</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkNotebook\"><property name=\"visible\">True</"
  "property><property name=\"can-focus\">True</property><property name=\"h"
  "expand\">True</property><property name=\"vexpand\">True</property><chil"
  "d><object class=\"GtkBox\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"margin-left"
  "\">12</property><property name=\"margin-right\">12</property><property "
  "name=\"margin-top\">12</property><property name=\"margin-bottom\">12</p"
  "roperty><property name=\"spacing\">6</property><child><object class=\"G"
  "tkBox\" id=\"display-settings\"><property name=\"visible\">True</proper"
  "ty><property name=\"can-focus\">False</property><property name=\"orient"
  "ation\">vertical</property><property name=\"spacing\">9</property><chil"
  "d><object class=\"GtkFrame\"><property name=\"visible\">True</property>"
  "<property name=\"can-focus\">False</property><property name=\"label-xal"
  "ign\">0</property><property name=\"label-yalign\">0</property><property"
  " name=\"shadow-type\">in</property><child><object class=\"GtkAlignment\""
  " id=\"randr-dnd\"><property name=\"width-request\">350</property><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property></object></child></object><packing><property name=\"expand\">"
  "True</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"mirror-displays\"><property name=\"label\" translatable="
  "\"yes\">_Mirror displays</property><property name=\"visible\">True</pro"
  "perty><property name=\"can-focus\">True</property><property name=\"rece"
  "ives-default\">False</property><property name=\"use-underline\">True</p"
  "roperty><property name=\"draw-indicator\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkGrid\" id=\"table1\"><property"
  " name=\"visible\">True</property><property name=\"can-focus\">False</pr"
  "operty><property name=\"row-spacing\">3</property><property name=\"colu"
  "mn-spacing\">3</property><child><object class=\"GtkBox\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">False</propert"
  "y><property name=\"margin-bottom\">3</property><property name=\"spacing"
  "\">12</property><child><object class=\"GtkComboBox\" id=\"randr-outputs"
  "\"><property name=\"visible\">True</property><property name=\"can-focus"
  "\">False</property><property name=\"hexpand\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">0</property></packing></c"
  "hild><child><object class=\"GtkSwitch\" id=\"output-on\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">True</property"
  "><property name=\"halign\">end</property><property name=\"valign\">cent"
  "er</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">1<"
  "/property></packing></child></object><packing><property name=\"left-att"
  "ach\">0</property><property name=\"top-attach\">0</property><property n"
  "ame=\"width\">4</property></packing></child><child><object class=\"GtkM"
  "enuButton\" id=\"primary-info-button\"><property name=\"visible\">True<"
  "/property><property name=\"can-focus\">True</property><property name=\""
  "receives-default\">True</property><property name=\"relief\">none</prope"
  "rty><property name=\"popover\">primary-info</property><property name=\""
  "image\">image8</property></object><packing><property name=\"left-attach"
  "\">3</property><property name=\"top-attach\">1</property></packing></ch"
  "ild><child><object class=\"GtkSwitch\" id=\"primary\"><property name=\""
  "visible\">True</property><property name=\"can-focus\">True</property><p"
  "roperty name=\"halign\">end</property><property name=\"valign\">center<"
  "/property><property name=\"margin-left\">9</property><property name=\"m"
  "argin-bottom\">3</property></object><packing><property name=\"left-atta"
  "ch\">2</property><property name=\"top-attach\">1</property></packing></"
  "child><child><object class=\"GtkLabel\" id=\"label-primary\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"halign\">start</property><property name=\"margin"
  "-bottom\">3</property><property name=\"label\" translatable=\"yes\">Pri"
  "mary Display:</property><property name=\"use-underline\">True</property"
  "></object><packing><property name=\"left-attach\">1</property><property"
  " name=\"top-attach\">1</property></packing></child><child><object class"
  "=\"GtkComboBox\" id=\"randr-resolution\"><property name=\"visible\">Tru"
  "e</property><property name=\"can-focus\">False</property><property name"
  "=\"margin-left\">9</property><property name=\"margin-bottom\">3</proper"
  "ty></object><packing><property name=\"left-attach\">2</property><proper"
  "ty name=\"top-attach\">2</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label-resolution\"><property name=\"visible\">True"
  "</property><property name=\"can-focus\">False</property><property name="
  "\"halign\">start</property><property name=\"margin-bottom\">3</property"
  "><property name=\"label\" translatable=\"yes\">R_esolution:</property><"
  "property name=\"use-underline\">True</property></object><packing><prope"
  "rty name=\"left-attach\">1</property><property name=\"top-attach\">2</p"
  "roperty></packing></child><child><object class=\"GtkComboBox\" id=\"ran"
  "dr-refresh-rate\"><property name=\"visible\">True</property><property n"
  "ame=\"can-focus\">False</property><property name=\"margin-left\">9</pro"
  "perty><property name=\"margin-bottom\">3</property></object><packing><p"
  "roperty name=\"left-attach\">2</property><property name=\"top-attach\">"
  "5</property></packing></child><child><object class=\"GtkLabel\" id=\"la"
  "bel-refresh-rate\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"halign\">start</pro"
  "perty><property name=\"margin-bottom\">3</property><property name=\"lab"
  "el\" translatable=\"yes\">Refresh _rate:</property><property name=\"use"
  "-underline\">True</property></object><packing><property name=\"left-att"
  "ach\">1</property><property name=\"top-attach\">5</property></packing><"
  "/child><child><object class=\"GtkComboBox\" id=\"randr-rotation\"><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">False"
  "</property><property name=\"margin-left\">9</property><property name=\""
  "margin-bottom\">3</property></object><packing><property name=\"left-att"
  "ach\">2</property><property name=\"top-attach\">6</property></packing><"
  "/child><child><object class=\"GtkLabel\" id=\"label-rotation\"><propert"
  "y name=\"visible\">True</property><property name=\"can-focus\">False</p"
  "roperty><property name=\"halign\">start</property><property name=\"marg"
  "in-bottom\">3</property><property name=\"label\" translatable=\"yes\">R"
  "o_tation:</property><property name=\"use-underline\">True</property></o"
  "bject><packing><property name=\"left-attach\">1</property><property nam"
  "e=\"top-attach\">6</property></packing></child><child><object class=\"G"
  "tkComboBox\" id=\"randr-reflection\"><property name=\"can-focus\">False"
  "</property><property name=\"margin-left\">9</property><property name=\""
  "margin-bottom\">3</property></object><packing><property name=\"left-att"
  "ach\">2</property><property name=\"top-attach\">7</property></packing><"
  "/child><child><object class=\"GtkLabel\" id=\"label-reflection\"><prope"
  "rty name=\"can-focus\">False</property><property name=\"halign\">start<"
  "/property><property name=\"margin-bottom\">3</property><property name=\""
  "label\" translatable=\"yes\">Ref_lection:</property><property name=\"us"
  "e-underline\">True</property></object><packing><property name=\"left-at"
  "tach\">1</property><property name=\"top-attach\">7</property></packing>"
  "</child><child><object class=\"GtkImage\" id=\"primary-indicator\"><pro"
  "perty name=\"visible\">True</property><property name=\"can-focus\">Fals"
  "e</property><property name=\"valign\">center</property><property name=\""
  "margin-left\">6</property><property name=\"pixel-size\">16</property><p"
  "roperty name=\"icon-name\">help-about-symbolic</property></object><pack"
  "ing><property name=\"left-attach\">0</property><property name=\"top-att"
  "ach\">1</property></packing></child><child><object class=\"GtkImage\" i"
  "d=\"dummy-icon\"><property name=\"visible\">True</property><property na"
  "me=\"can-focus\">False</property><property name=\"margin-left\">6</prop"
  "erty><property name=\"pixel-size\">16</property></object><packing><prop"
  "erty name=\"left-attach\">0</property><property name=\"top-attach\">2</"
  "property></packing></child><child><object class=\"GtkBox\" id=\"hbox1\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><child><object class=\"GtkButton\" id=\"apply\"><prope"
  "rty name=\"label\" translatable=\"yes\">A_pply</property><property name"
  "=\"visible\">True</property><property name=\"can-focus\">True</property"
  "><property name=\"receives-default\">True</property><property name=\"ma"
  "rgin-top\">6</property><property name=\"image\">image4</property><prope"
  "rty name=\"use-underline\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"pack-type\">end</property><property name=\"position\">1"
  "</property></packing></child></object><packing><property name=\"left-at"
  "tach\">0</property><property name=\"top-attach\">8</property><property "
  "name=\"width\">3</property></packing></child><child><object class=\"Gtk"
  "Label\" id=\"label-scale\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"margin-bott"
  "om\">3</property><property name=\"halign\">start</property><property na"
  "me=\"label\" translatable=\"yes\">_Scale:</property><property name=\"us"
  "e-underline\">True</property></object><packing><property name=\"left-at"
  "tach\">1</property><property name=\"top-attach\">3</property></packing>"
  "</child><child><object class=\"GtkSpinButton\" id=\"spin-scale\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">True</"
  "property><property name=\"margin-left\">9</property><property name=\"ma"
  "rgin-bottom\">3</property><property name=\"adjustment\">adjustment1</pr"
  "operty><property name=\"digits\">2</property><property name=\"numeric\""
  ">True</property><property name=\"value\">1.00</property></object><packi"
  "ng><property name=\"left-attach\">2</property><property name=\"top-atta"
  "ch\">3</property></packing></child></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">True</property><propert"
  "y name=\"pack-type\">end</property><property name=\"position\">1</prope"
  "rty></packing></child></object></child><child type=\"tab\"><object clas"
  "s=\"GtkLabel\"><property name=\"visible\">True</property><property name"
  "=\"can-focus\">False</property><property name=\"label\" translatable=\""
  "yes\">_General</property><property name=\"use-underline\">True</propert"
  "y></object><packing><property name=\"tab-fill\">False</property></packi"
  "ng></child><child><object class=\"GtkGrid\"><property name=\"visible\">"
  "True</property><property name=\"can-focus\">False</property><property n"
  "ame=\"border-width\">12</property><property name=\"row-spacing\">6</pro"
  "perty><property name=\"column-spacing\">12</property><child><object cla"
  "ss=\"GtkLabel\" id=\"label-profile\"><property name=\"visible\">True</p"
  "roperty><property name=\"can-focus\">False</property><property name=\"h"
  "align\">start</property><property name=\"label\" translatable=\"yes\">&"
  "lt;b&gt;Profiles&lt;/b&gt;</property><property name=\"use-markup\">True"
  "</property><property name=\"use-underline\">True</property></object><pa"
  "cking><property name=\"left-attach\">0</property><property name=\"top-a"
  "ttach\">0</property><property name=\"width\">2</property></packing></ch"
  "ild><child><object class=\"GtkLabel\" id=\"label-profile1\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">False</prop"
  "erty><property name=\"halign\">start</property><property name=\"margin-"
  "top\">12</property><property name=\"label\" translatable=\"yes\">&lt;b&"
  "gt;Connecting Displays&lt;/b&gt;</property><property name=\"use-markup\""
  ">True</property><property name=\"use-underline\">True</property></objec"
  "t><packing><property name=\"left-attach\">0</property><property name=\""
  "top-attach\">2</property><property name=\"width\">2</property></packing"
  "></child><child><object class=\"GtkBox\"><property name=\"visible\">Tru"
  "e</property><property name=\"can-focus\">False</property><property name"
  "=\"margin-left\">12</property><property name=\"hexpand\">True</property"
  "><property name=\"orientation\">vertical</property><child><object class"
  "=\"GtkScrolledWindow\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">True</property><property name=\"shadow-type\">in"
  "</property><child><object class=\"GtkTreeView\" id=\"randr-profile\"><p"
  "roperty name=\"visible\">True</property><property name=\"can-focus\">Tr"
  "ue</property><property name=\"hexpand\">True</property><property name=\""
  "vexpand\">True</property><property name=\"border-width\">1</property><c"
  "hild internal-child=\"selection\"><object class=\"GtkTreeSelection\"/><"
  "/child></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkBox\">"
  "<property name=\"visible\">True</property><property name=\"can-focus\">"
  "False</property><child><object class=\"GtkButton\" id=\"button-profile-"
  "delete\"><property name=\"visible\">True</property><property name=\"can"
  "-focus\">True</property><property name=\"receives-default\">True</prope"
  "rty><property name=\"tooltip-text\" translatable=\"yes\">Delete the cur"
  "rently selected display profile.</property><property name=\"image\">ima"
  "ge1</property><property name=\"always-show-image\">True</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"pack-type\">end</property><prope"
  "rty name=\"position\">-1</property></packing></child><child><object cla"
  "ss=\"GtkButton\" id=\"button-profile-apply\"><property name=\"label\" t"
  "ranslatable=\"yes\">Apply</property><property name=\"visible\">True</pr"
  "operty><property name=\"can-focus\">True</property><property name=\"rec"
  "eives-default\">True</property><property name=\"tooltip-text\" translat"
  "able=\"yes\">Apply the currently selected display profile.</property><p"
  "roperty name=\"image\">image7</property><property name=\"always-show-im"
  "age\">True</property></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"pack-"
  "type\">end</property><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"button-profile-create\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">True</property><property name=\"receives-default\">True</property><pro"
  "perty name=\"tooltip-text\" translatable=\"yes\">Create a new display p"
  "rofile.</property><property name=\"image\">image5</property><property n"
  "ame=\"always-show-image\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"pack-type\">end</property><property name=\"position\">1<"
  "/property></packing></child><child><object class=\"GtkButton\" id=\"but"
  "ton-profile-save\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">True</property><property name=\"receives-default\">T"
  "rue</property><property name=\"tooltip-text\" translatable=\"yes\">Upda"
  "te an existing profile.</property><property name=\"image\">image2</prop"
  "erty><property name=\"always-show-image\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"pack-type\">end</property><property name"
  "=\"position\">2</property></packing></child><style><class name=\"inline"
  "-toolbar\"/></style></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child></object><packing><property name=\"l"
  "eft-attach\">0</property><property name=\"top-attach\">1</property><pro"
  "perty name=\"width\">2</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"auto-enable-profiles-label\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"margin-left\">12</property><property name=\"label\" translata"
  "ble=\"yes\">First try to automatically enable a profile:</property><pro"
  "perty name=\"xalign\">0</property></object><packing><property name=\"le"
  "ft-attach\">0</property><property name=\"top-attach\">4</property></pac"
  "king></child><child><object class=\"GtkComboBox\" id=\"auto-enable-prof"
  "iles\"><property name=\"visible\">True</property><property name=\"can-f"
  "ocus\">False</property><property name=\"valign\">center</property><prop"
  "erty name=\"model\">liststore1</property><property name=\"id-column\">1"
  "</property><child><object class=\"GtkCellRendererText\" id=\"cellrender"
  "ertext1\"/><attributes><attribute name=\"text\">0</attribute></attribut"
  "es></child></object><packing><property name=\"left-attach\">1</property"
  "><property name=\"top-attach\">4</property></packing></child><child><ob"
  "ject class=\"GtkLabel\"><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><property name=\"margin-left\">"
  "12</property><property name=\"label\" translatable=\"yes\">When a displ"
  "ay is connected:</property><property name=\"xalign\">0</property></obje"
  "ct><packing><property name=\"left-attach\">0</property><property name=\""
  "top-attach\">3</property></packing></child><child><object class=\"GtkLa"
  "bel\" id=\"identify-displays-label\"><property name=\"visible\">True</p"
  "roperty><property name=\"can-focus\">False</property><property name=\"m"
  "argin-left\">12</property><property name=\"label\" translatable=\"yes\""
  ">Show popup windows to identify displays</property><property name=\"xal"
  "ign\">0</property></object><packing><property name=\"left-attach\">0</p"
  "roperty><property name=\"top-attach\">6</property></packing></child><ch"
  "ild><object class=\"GtkSwitch\" id=\"identify-displays\"><property name"
  "=\"visible\">True</property><property name=\"can-focus\">True</property"
  "><property name=\"halign\">end</property><property name=\"valign\">cent"
  "er</property></object><packing><property name=\"left-attach\">1</proper"
  "ty><property name=\"top-attach\">6</property></packing></child><child><"
  "object class=\"GtkLabel\" id=\"label-profile2\"><property name=\"visibl"
  "e\">True</property><property name=\"can-focus\">False</property><proper"
  "ty name=\"halign\">start</property><property name=\"margin-top\">12</pr"
  "operty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Identifyi"
  "ng Displays&lt;/b&gt;</property><property name=\"use-markup\">True</pro"
  "perty><property name=\"use-underline\">True</property></object><packing"
  "><property name=\"left-attach\">0</property><property name=\"top-attach"
  "\">5</property><property name=\"width\">2</property></packing></child><"
  "child><object class=\"GtkComboBox\" id=\"autoconnect-mode\"><property n"
  "ame=\"visible\">True</property><property name=\"can-focus\">False</prop"
  "erty><property name=\"valign\">center</property><property name=\"model\""
  ">liststore2</property><property name=\"id-column\">1</property><child><"
  "object class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attribu"
  "tes><attribute name=\"text\">0</attribute></attributes></child></object"
  "><packing><property name=\"left-attach\">1</property><property name=\"t"
  "op-attach\">3</property></packing></child></object><packing><property n"
  "ame=\"position\">1</property></packing></child><child type=\"tab\"><obj"
  "ect class=\"GtkLabel\"><property name=\"visible\">True</property><prope"
  "rty name=\"can-focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">_Advanced</property><property name=\"use-underline\">True"
  "</property></object><packing><property name=\"position\">1</property><p"
  "roperty name=\"tab-fill\">False</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">2</property><"
  "/packing></child></object></child><action-widgets><action-widget respon"
  "se=\"-11\">button-help</action-widget><action-widget response=\"-7\">bu"
  "tton-close</action-widget></action-widgets></object><object class=\"Gtk"
  "Popover\" id=\"popover-create-profile\"><property name=\"can-focus\">Fa"
  "lse</property><property name=\"relative-to\">button-profile-create</pro"
  "perty><child><object class=\"GtkBox\"><property name=\"visible\">True</"
  "property><property name=\"can-focus\">False</property><property name=\""
  "orientation\">vertical</property><child><object class=\"GtkGrid\"><prop"
  "erty name=\"visible\">True</property><property name=\"can-focus\">False"
  "</property><property name=\"margin-left\">12</property><property name=\""
  "margin-right\">12</property><property name=\"margin-top\">12</property>"
  "<property name=\"margin-bottom\">24</property><property name=\"row-spac"
  "ing\">6</property><property name=\"column-spacing\">6</property><child>"
  "<object class=\"GtkLabel\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">&lt;b&gt;Profile Name&lt;/b&gt;</property><property n"
  "ame=\"use-markup\">True</property><property name=\"xalign\">0</property"
  "></object><packing><property name=\"left-attach\">0</property><property"
  " name=\"top-attach\">0</property></packing></child><child><object class"
  "=\"GtkEntry\" id=\"entry-profile-create\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can-focus\">True</property><property name"
  "=\"hexpand\">True</property><property name=\"activates-default\">True</"
  "property></object><packing><property name=\"left-attach\">0</property><"
  "property name=\"top-attach\">1</property></packing></child><child><obje"
  "ct class=\"GtkButton\" id=\"button-profile-create-cb\"><property name=\""
  "label\" translatable=\"yes\">Create</property><property name=\"visible\""
  ">True</property><property name=\"can-focus\">True</property><property n"
  "ame=\"can-default\">True</property><property name=\"has-default\">True<"
  "/property><property name=\"receives-default\">True</property><style><cl"
  "ass name=\"suggested-action\"/></style></object><packing><property name"
  "=\"left-attach\">1</property><property name=\"top-attach\">1</property>"
  "</packing></child><child><object class=\"GtkBox\" id=\"profile-exists\""
  "><property name=\"visible\">True</property><property name=\"can-focus\""
  ">False</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkImage\"><property name=\"visible\">True</property><property "
  "name=\"can-focus\">False</property><property name=\"icon-name\">dialog-"
  "error-symbolic</property></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkLabel\""
  "><property name=\"can-focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">A profile of this name already exists.</property><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object><packing><property name=\"left-attach\">0</proper"
  "ty><property name=\"top-attach\">2</property><property name=\"width\">2"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child></object></child></object></"
  "interface>"
};

static const unsigned display_dialog_ui_length = 32114u;

