/* automatically generated from minimal-display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (minimal_display_dialog_ui)
#endif
#ifdef __GNUC__
static const char minimal_display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char minimal_display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkImage\" id=\"image-cancel-but"
  "ton\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"icon_name\">window-close-symboli"
  "c</property></object><object class=\"GtkListStore\" id=\"liststore-exte"
  "nd\"><columns><column type=\"gchararray\"/></columns><data><row><col id"
  "=\"0\" translatable=\"yes\">Extend right</col></row><row><col id=\"0\" "
  "translatable=\"yes\">Extend left</col></row><row><col id=\"0\" translat"
  "able=\"yes\">Extend up</col></row><row><col id=\"0\" translatable=\"yes"
  "\">Extend down</col></row></data></object><object class=\"GtkListStore\""
  " id=\"liststore-profile\"><columns><column type=\"gchararray\"/><column"
  " type=\"gchararray\"/></columns></object><object class=\"GtkWindow\" id"
  "=\"dialog\"><property name=\"can_focus\">False</property><property name"
  "=\"title\" translatable=\"yes\">Displays</property><property name=\"win"
  "dow_position\">center</property><property name=\"icon_name\">org.xfce.s"
  "ettings.display</property><property name=\"type_hint\">dialog</property"
  "><child><placeholder/></child><child><object class=\"GtkBox\" id=\"vbox"
  "1\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"border_width\">6</property><proper"
  "ty name=\"orientation\">vertical</property><property name=\"spacing\">6"
  "</property><child><object class=\"GtkGrid\" id=\"buttons\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"row_spacing\">6</property><property name=\"column_"
  "spacing\">24</property><child><object class=\"GtkBox\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"hexpand\">True</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">3</property><child><obje"
  "ct class=\"GtkRadioButton\" id=\"display1\"><property name=\"width_requ"
  "est\">128</property><property name=\"height_request\">128</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"halign\">center</property><property name=\"active\">True</pro"
  "perty><property name=\"draw_indicator\">False</property><child><object "
  "class=\"GtkImage\" id=\"image-display1\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkLabel\" id=\"label-display1"
  "\"><property name=\"width_request\">128</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"tooltip_text\" translatable=\"yes\">Only Display 1</propert"
  "y><property name=\"label\" translatable=\"yes\">Only Display 1</propert"
  "y><property name=\"ellipsize\">middle</property><property name=\"max-wi"
  "dth-chars\">0</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object><packing><property name"
  "=\"left_attach\">0</property><property name=\"top_attach\">0</property>"
  "</packing></child><child><object class=\"GtkBox\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"hexpand\">True</property><property name=\"orientation\">ver"
  "tical</property><property name=\"spacing\">3</property><child><object c"
  "lass=\"GtkRadioButton\" id=\"mirror\"><property name=\"width_request\">"
  "128</property><property name=\"height_request\">128</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"halign\">center</property><property name=\"active\">True</property>"
  "<property name=\"draw_indicator\">False</property><property name=\"grou"
  "p\">display1</property><child><object class=\"GtkImage\" id=\"image-mir"
  "ror\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property></object></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"label-mirror\"><property name=\"width_request\">1"
  "28</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"tooltip_text\" translatabl"
  "e=\"yes\">Mirror Displays</property><property name=\"label\" translatab"
  "le=\"yes\">Mirror Displays</property><property name=\"ellipsize\">middl"
  "e</property><property name=\"max-width-chars\">0</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"left_attach\">1</property><proper"
  "ty name=\"top_attach\">0</property></packing></child><child><object cla"
  "ss=\"GtkBox\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"hexpand\">True</property"
  "><property name=\"orientation\">vertical</property><property name=\"spa"
  "cing\">3</property><child><object class=\"GtkRadioButton\" id=\"extend\""
  "><property name=\"width_request\">128</property><property name=\"height"
  "_request\">128</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"receives_defau"
  "lt\">False</property><property name=\"halign\">center</property><proper"
  "ty name=\"active\">True</property><property name=\"draw_indicator\">Fal"
  "se</property><property name=\"group\">display1</property><child><object"
  " class=\"GtkImage\" id=\"image-extend\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property></object></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkComboBox\" id=\"combobox-ext"
  "end\"><property name=\"width_request\">128</property><property name=\"v"
  "isible\">True</property><property name=\"can-focus\">False</property><p"
  "roperty name=\"valign\">center</property><property name=\"model\">lists"
  "tore-extend</property><property name=\"active\">0</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Extend to the right</property"
  "><child><object class=\"GtkCellRendererText\"><property name=\"ellipsiz"
  "e\">middle</property><property name=\"ellipsize-set\">True</property><p"
  "roperty name=\"max-width-chars\">1</property><property name=\"xalign\">"
  "0.5</property></object><attributes><attribute name=\"text\">0</attribut"
  "e></attributes></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"left_attach\">2</property><property name=\"top_attach\">0</property><"
  "/packing></child><child><object class=\"GtkBox\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"hexpand\">True</property><property name=\"orientation\">vert"
  "ical</property><property name=\"spacing\">3</property><child><object cl"
  "ass=\"GtkRadioButton\" id=\"display2\"><property name=\"width_request\""
  ">128</property><property name=\"height_request\">128</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"halign\">center</property><property name=\"active\">True</property"
  "><property name=\"draw_indicator\">False</property><property name=\"gro"
  "up\">display1</property><child><object class=\"GtkImage\" id=\"image-di"
  "splay2\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkLabel\" id=\"label-display2\"><property name=\"width_reques"
  "t\">128</property><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">Only Display 2</property><property name=\"label\" trans"
  "latable=\"yes\">Only Display 2</property><property name=\"ellipsize\">m"
  "iddle</property><property name=\"max-width-chars\">0</property></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"left_attach\">3</property><pr"
  "operty name=\"top_attach\">0</property></packing></child><child><object"
  " class=\"GtkBox\" id=\"box-profile\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"h"
  "expand\">True</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">3</property><child><object class=\"GtkRad"
  "ioButton\" id=\"profile\"><property name=\"width_request\">128</propert"
  "y><property name=\"height_request\">128</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">False</property><property name=\"halign\""
  ">center</property><property name=\"active\">True</property><property na"
  "me=\"draw_indicator\">False</property><property name=\"group\">display1"
  "</property><child><object class=\"GtkImage\" id=\"image-profile\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkCo"
  "mboBox\" id=\"combobox-profile\"><property name=\"width_request\">128</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "-focus\">False</property><property name=\"valign\">center</property><pr"
  "operty name=\"model\">liststore-profile</property><child><object class="
  "\"GtkCellRendererText\"><property name=\"ellipsize\">middle</property><"
  "property name=\"ellipsize-set\">True</property><property name=\"max-wid"
  "th-chars\">1</property><property name=\"xalign\">0.5</property></object"
  "><attributes><attribute name=\"text\">0</attribute></attributes></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child></object><packing><property name=\"left_attach\">4</pro"
  "perty><property name=\"top_attach\">0</property></packing></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkButtonBox\" id=\"hbuttonbox1\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><child><object class=\"GtkButton\" id=\"advanced-button\"><p"
  "roperty name=\"label\" translatable=\"yes\">_Advanced</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">True</property><property na"
  "me=\"use_underline\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkButton\" id=\"cancel-button\"><property name=\"label\" translata"
  "ble=\"yes\">_Close</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">True</property><property name=\"image\">image-cancel-button</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"pack_type\">end</property"
  "><property name=\"position\">1</property></packing></child></object></c"
  "hild></object></interface>"
};

static const unsigned minimal_display_dialog_ui_length = 11741u;

