/* automatically generated from mouse-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (mouse_dialog_ui)
#endif
#ifdef __GNUC__
static const char mouse_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char mouse_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.13\"/"
  "><object class=\"GtkAdjustment\" id=\"dclick-distance\"><property name="
  "\"upper\">20</property><property name=\"value\">4</property><property n"
  "ame=\"step_increment\">1</property><property name=\"page_increment\">5<"
  "/property></object><object class=\"GtkAdjustment\" id=\"dclick-time\"><"
  "property name=\"lower\">100</property><property name=\"upper\">2000</pr"
  "operty><property name=\"value\">250</property><property name=\"step_inc"
  "rement\">1</property><property name=\"page_increment\">100</property></"
  "object><object class=\"GtkAdjustment\" id=\"device-acceleration\"><prop"
  "erty name=\"upper\">10</property><property name=\"value\">2</property><"
  "property name=\"step_increment\">0.10000000000000001</property><propert"
  "y name=\"page_increment\">1</property></object><object class=\"GtkAdjus"
  "tment\" id=\"device-threshold\"><property name=\"lower\">1</property><p"
  "roperty name=\"upper\">30</property><property name=\"value\">4</propert"
  "y><property name=\"step_increment\">1</property><property name=\"page_i"
  "ncrement\">5</property></object><object class=\"GtkAdjustment\" id=\"dn"
  "d-threshold\"><property name=\"lower\">1</property><property name=\"upp"
  "er\">50</property><property name=\"value\">8</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkImage\" id=\"image1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"icon_name\">window-close-symbolic</property></object><o"
  "bject class=\"GtkImage\" id=\"image2\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "icon_name\">help-browser</property></object><object class=\"GtkImage\" "
  "id=\"image5\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"stock\">gtk-revert-to-sa"
  "ved</property></object><object class=\"GtkListStore\" id=\"libinput-cli"
  "ck-methods-store\"><columns><column type=\"gchararray\"/><column type=\""
  "gboolean\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Non"
  "e</col><col id=\"1\">True</col></row><row><col id=\"0\" translatable=\""
  "yes\">Use bottom areas as left, middle or right buttons</col><col id=\""
  "1\">True</col></row><row><col id=\"0\" translatable=\"yes\">Click with "
  "1, 2 or 3 fingers as a left, right, or middle click</col><col id=\"1\">"
  "True</col></row></data></object><object class=\"GtkAdjustment\" id=\"sy"
  "naptics-disable-duration\"><property name=\"lower\">0.10000000000000001"
  "</property><property name=\"upper\">4</property><property name=\"value\""
  ">2</property><property name=\"step_increment\">0.10000000000000001</pro"
  "perty><property name=\"page_increment\">1</property></object><object cl"
  "ass=\"GtkListStore\" id=\"synaptics-scroll-store\"><columns><column typ"
  "e=\"gchararray\"/><column type=\"gboolean\"/></columns><data><row><col "
  "id=\"0\" translatable=\"yes\">Disabled</col><col id=\"1\">True</col></r"
  "ow><row><col id=\"0\" translatable=\"yes\">Edge scrolling</col><col id="
  "\"1\">True</col></row><row><col id=\"0\" translatable=\"yes\">Two-finge"
  "r scrolling</col><col id=\"1\">True</col></row><row><col id=\"0\" trans"
  "latable=\"yes\">Circular scrolling</col><col id=\"1\">True</col></row><"
  "/data></object><object class=\"GtkAdjustment\" id=\"theme-cursor-size\""
  "><property name=\"lower\">16</property><property name=\"upper\">72</pro"
  "perty><property name=\"value\">24</property><property name=\"step_incre"
  "ment\">1</property><property name=\"page_increment\">11</property></obj"
  "ect><object class=\"GtkListStore\" id=\"wacom-mode-store\"><columns><co"
  "lumn type=\"gchararray\"/><column type=\"gchararray\"/></columns><data>"
  "<row><col id=\"0\">ABSOLUTE</col><col id=\"1\" translatable=\"yes\">Pen"
  " (absolute)</col></row><row><col id=\"0\">RELATIVE</col><col id=\"1\" t"
  "ranslatable=\"yes\">Mouse (relative)</col></row></data></object><object"
  " class=\"GtkListStore\" id=\"wacom-rotation-store\"><columns><column ty"
  "pe=\"gint\"/><column type=\"gchararray\"/></columns><data><row><col id="
  "\"0\">0</col><col id=\"1\" translatable=\"yes\">None (right-handed)</co"
  "l></row><row><col id=\"0\">3</col><col id=\"1\" translatable=\"yes\">Ha"
  "lf (left-handed)</col></row><row><col id=\"0\">1</col><col id=\"1\" tra"
  "nslatable=\"yes\">Clockwise</col></row><row><col id=\"0\">2</col><col i"
  "d=\"1\" translatable=\"yes\">Counterclockwise</col></row></data></objec"
  "t><object class=\"XfceTitledDialog\" id=\"mouse-dialog\"><property name"
  "=\"can_focus\">False</property><property name=\"title\" translatable=\""
  "yes\">Mouse and Touchpad</property><property name=\"window_position\">c"
  "enter-on-parent</property><property name=\"icon_name\">org.xfce.setting"
  "s.mouse</property><property name=\"type_hint\">dialog</property><child "
  "internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vbox1\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">2</property><child internal-child=\"action_area\"><"
  "object class=\"GtkButtonBox\" id=\"dialog-action_area1\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"layout_style\">end</property><child><object class=\""
  "GtkButton\" id=\"button2\"><property name=\"label\" translatable=\"yes\""
  ">_Help</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Tru"
  "e</property><property name=\"image\">image2</property><property name=\""
  "use_underline\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">False</property><property n"
  "ame=\"position\">0</property><property name=\"secondary\">True</propert"
  "y></packing></child><child><object class=\"GtkButton\" id=\"button1\"><"
  "property name=\"label\" translatable=\"yes\">_Close</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">True</property><property name"
  "=\"image\">image1</property><property name=\"use_underline\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">0</proper"
  "ty></packing></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"pack_"
  "type\">end</property><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkNotebook\" id=\"plug-child\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"border_width\">6</property><child><object class"
  "=\"GtkBox\" id=\"vbox1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">12</property><child><object class=\"GtkBox\" id=\"h"
  "box1\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"spacing\">12</property><child><"
  "object class=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">De_vice:</property><property name=\"use_"
  "underline\">True</property><property name=\"mnemonic_widget\">device-co"
  "mbobox</property><property name=\"angle\">0.050000000000000003</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkComboBox\" id=\"device-combo"
  "box\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkSwitch\" "
  "id=\"device-enabled\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"valign\">center</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">2</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkNotebo"
  "ok\" id=\"device-notebook\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><child><object class=\"GtkBo"
  "x\" id=\"device-box\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"border_width\">1"
  "2</property><property name=\"orientation\">vertical</property><property"
  " name=\"spacing\">18</property><child><object class=\"GtkFrame\" id=\"f"
  "rame1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class=\"GtkAl"
  "ignment\" id=\"alignment1\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"top_paddin"
  "g\">6</property><property name=\"left_padding\">12</property><child><ob"
  "ject class=\"GtkBox\" id=\"vbox12\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"or"
  "ientation\">vertical</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkBox\" id=\"hbox3\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"spacing\">12</property><child><object class=\"GtkRadioButton\" id"
  "=\"device-left-handed\"><property name=\"label\" translatable=\"yes\">L"
  "e_ft-handed</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"halign\">start</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property><property name=\"group\">device-right-handed</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkRadioButton\" id=\"device-right-"
  "handed\"><property name=\"label\" translatable=\"yes\">Ri_ght-handed</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"halign\">start</property><property name=\"use_unde"
  "rline\">True</property><property name=\"active\">True</property><proper"
  "ty name=\"draw_indicator\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkCheckButton\" id=\"device-reverse-scrolling\""
  "><property name=\"label\" translatable=\"yes\">Reverse scroll d_irectio"
  "n</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"tooltip_text\" translatable=\"yes\">When selec"
  "ted, the scroll wheel will work in the opposite direction</property><pr"
  "operty name=\"halign\">start</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">True</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child><child><object class=\"GtkCheckButton\" id=\"libinput-hires-scr"
  "olling\"><property name=\"label\" translatable=\"yes\">Allow high _reso"
  "lution scrolling (experimental)</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"tooltip_text\" t"
  "ranslatable=\"yes\">Only supported on some mice (mostly Logitech) and r"
  "equires driver support. On supported devices makes scrolling more preci"
  "se.</property><property name=\"halign\">start</property><property name="
  "\"use_underline\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">2</pr"
  "operty></packing></child></object></child></object></child><child type="
  "\"label\"><object class=\"GtkLabel\" id=\"label14\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">Buttons</property><attribute"
  "s><attribute name=\"weight\" value=\"bold\"/></attributes></object></ch"
  "ild></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkFrame\" id=\"frame2\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label_xalign\">0</property><property name="
  "\"shadow_type\">none</property><child><object class=\"GtkAlignment\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"top_padding\">6</property><property name"
  "=\"left_padding\">12</property><child><object class=\"GtkGrid\" id=\"gr"
  "id1\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"row_spacing\">6</property><prope"
  "rty name=\"column_spacing\">12</property><child><object class=\"GtkButt"
  "on\" id=\"device-reset-feedback\"><property name=\"label\" translatable"
  "=\"yes\">_Reset to Defaults</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"tooltip_text\" transl"
  "atable=\"yes\">Set the acceleration and sensitivity for the selected de"
  "vice to the default values</property><property name=\"halign\">start</p"
  "roperty><property name=\"image\">image5</property><property name=\"use_"
  "underline\">True</property></object><packing><property name=\"left_atta"
  "ch\">0</property><property name=\"top_attach\">3</property><property na"
  "me=\"width\">2</property></packing></child><child><object class=\"GtkLa"
  "bel\" id=\"device-threshold-label\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ha"
  "lign\">start</property><property name=\"label\" translatable=\"yes\">Se"
  "nsitivit_y:</property><property name=\"use_underline\">True</property><"
  "/object><packing><property name=\"left_attach\">0</property><property n"
  "ame=\"top_attach\">1</property></packing></child><child><object class=\""
  "GtkLabel\" id=\"device-acceleration-label\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"halign\">start</property><property name=\"label\" translatable=\""
  "yes\">Acceleratio_n:</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"left_attach\">0</property><p"
  "roperty name=\"top_attach\">0</property></packing></child><child><objec"
  "t class=\"GtkScale\" id=\"device-acceleration-scale\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"tooltip_text\" translatable=\"yes\">The factor at which "
  "the pointer\'s speed will increase as the mouse is moved</property><pro"
  "perty name=\"hexpand\">True</property><property name=\"adjustment\">dev"
  "ice-acceleration</property><property name=\"round_digits\">1</property>"
  "<property name=\"value_pos\">right</property></object><packing><propert"
  "y name=\"left_attach\">1</property><property name=\"top_attach\">0</pro"
  "perty></packing></child><child><object class=\"GtkScale\" id=\"device-t"
  "hreshold-scale\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">The number of pixels the pointer must move in a short tim"
  "e before it starts accelerating</property><property name=\"hexpand\">Tr"
  "ue</property><property name=\"adjustment\">device-threshold</property><"
  "property name=\"round_digits\">0</property><property name=\"digits\">0<"
  "/property><property name=\"value_pos\">right</property></object><packin"
  "g><property name=\"left_attach\">1</property><property name=\"top_attac"
  "h\">1</property></packing></child><child><object class=\"GtkCheckButton"
  "\" id=\"libinput-accel-profile\"><property name=\"label\" translatable="
  "\"yes\">Adaptive pointer acceleration</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"tooltip_text\" translatable=\"yes\">Toggles between adaptive a"
  "nd flat acceleration profile. Adaptive takes the current speed of the d"
  "evice into account when deciding on acceleration. Custom acceleration p"
  "rofile is not supported via xfce4-settings.</property><property name=\""
  "receives_default\">False</property><property name=\"halign\">start</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"left"
  "_attach\">0</property><property name=\"top_attach\">2</property><proper"
  "ty name=\"width\">2</property></packing></child></object></child></obje"
  "ct></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label1"
  "5\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label\" translatable=\"yes\">Point"
  "er Speed</property><attributes><attribute name=\"weight\" value=\"bold\""
  "/></attributes></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child></object></child><child "
  "type=\"tab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">B_uttons and Feedback</pro"
  "perty><property name=\"use_underline\">True</property></object><packing"
  "><property name=\"tab_fill\">False</property></packing></child><child><"
  "object class=\"GtkBox\" id=\"synaptics-tab\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"border_width\">12</property><property name=\"orientation\">verti"
  "cal</property><property name=\"spacing\">18</property><child><object cl"
  "ass=\"GtkFrame\" id=\"frame11\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label_"
  "xalign\">0</property><property name=\"shadow_type\">none</property><chi"
  "ld><object class=\"GtkAlignment\" id=\"alignment13\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"top_padding\">6</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkBox\" id=\"vbox11\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"orientation\">vertical</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"syna"
  "ptics-disable-while-type\"><property name=\"label\" translatable=\"yes\""
  ">Disable touchpad _while typing</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"tooltip_text\" t"
  "ranslatable=\"yes\">When selected, the touchpad will be disabled when t"
  "he keyboard is being used</property><property name=\"halign\">start</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kCheckButton\" id=\"libinput-disable-while-type\"><property name=\"labe"
  "l\" translatable=\"yes\">Disable touchpad _while typing</property><prop"
  "erty name=\"visible\">False</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"tooltip_text\" translatable=\"yes\">When selected, the touchpa"
  "d will be disabled when the keyboard is being used</property><property "
  "name=\"halign\">start</property><property name=\"use_underline\">True</"
  "property><property name=\"draw_indicator\">True</property></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "><child><object class=\"GtkAlignment\" id=\"alignment8\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"left_padding\">12</property><child><object class=\"G"
  "tkBox\" id=\"synaptics-disable-duration-box\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"la"
  "bel5\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">Du"
  "ratio_n:</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"mnemonic_widget\">synaptics-disable-duration-scale</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkScale\" id=\"synaptics-disa"
  "ble-duration-scale\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"adjustment\">synap"
  "tics-disable-duration</property><property name=\"round_digits\">1</prop"
  "erty><property name=\"value_pos\">right</property></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t></child></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">2</pro"
  "perty></packing></child><child><object class=\"GtkCheckButton\" id=\"sy"
  "naptics-tap-to-click\"><property name=\"label\" translatable=\"yes\">Ta"
  "p touchpad to clic_k</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"halign\">start</property><p"
  "roperty name=\"use_underline\">True</property><property name=\"draw_ind"
  "icator\">True</property></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">3</property></packing></child><child><object class=\"GtkBox\" i"
  "d=\"hbox5\"><property name=\"visible\">True</property><property name=\""
  "can-focus\">False</property><property name=\"spacing\">12</property><ch"
  "ild><object class=\"GtkLabel\" id=\"libinput-click-method-label\"><prop"
  "erty name=\"visible\">False</property><property name=\"can-focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">Click m_ethod"
  ":</property><property name=\"use_underline\">True</property><property n"
  "ame=\"mnemonic_widget\">libinput-click-method-box</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkComboBox\" id=\"libinput-click-method-box\""
  "><property name=\"visible\">False</property><property name=\"can-focus\""
  ">False</property><property name=\"model\">libinput-click-methods-store<"
  "/property><child><object class=\"GtkCellRendererText\" id=\"cellrendere"
  "rtext4\"/><attributes><attribute name=\"text\">0</attribute><attribute "
  "name=\"sensitive\">1</attribute></attributes></child></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">4</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label16\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">General</property><property name=\"use_marku"
  "p\">True</property><attributes><attribute name=\"weight\" value=\"bold\""
  "/></attributes></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkFrame\" id=\"frame10\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label_xalign\""
  ">0</property><property name=\"shadow_type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment12\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"top_padding\">6</property><property name=\"left_padding\">12</pr"
  "operty><child><object class=\"GtkBox\" id=\"vbox10\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"orientation\">vertical</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkBox\" id=\"hbox4\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"spacing\">12</property><child><object class=\"Gt"
  "kLabel\" id=\"label23\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">Scrolling _mode:</property><property name=\"use_underlin"
  "e\">True</property><property name=\"mnemonic_widget\">synaptics-scroll<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkComboBox\" id=\"syna"
  "ptics-scroll\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"model\">synaptics-scrol"
  "l-store</property><child><object class=\"GtkCellRendererText\" id=\"cel"
  "lrenderertext3\"/><attributes><attribute name=\"sensitive\">1</attribut"
  "e><attribute name=\"text\">0</attribute></attributes></child></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"synaptics"
  "-scroll-horiz\"><property name=\"label\" translatable=\"yes\">Enable ho"
  "ri_zontal scrolling</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">False</property><property name=\"halign\">start</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"draw_indi"
  "cator\">True</property></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">1</property></packing></child></object></child></object></child>"
  "<child type=\"label\"><object class=\"GtkLabel\" id=\"label17\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">Scrolling</prope"
  "rty><property name=\"use_markup\">True</property><attributes><attribute"
  " name=\"weight\" value=\"bold\"/></attributes></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object><packing><property name=\"position\">1</property></pack"
  "ing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"synapti"
  "cs-label\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">T_ouchpad</property><property name=\"use_underline\">True</property></"
  "object><packing><property name=\"position\">1</property><property name="
  "\"tab_fill\">False</property></packing></child><child><object class=\"G"
  "tkBox\" id=\"wacom-tab\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"orientation\">vertical</property><proper"
  "ty name=\"spacing\">6</property><child><object class=\"GtkFrame\" id=\""
  "frame12\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label_xalign\">0</property><"
  "property name=\"shadow_type\">none</property><child><object class=\"Gtk"
  "Alignment\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"top_padding\">6</property>"
  "<property name=\"left_padding\">12</property><child><object class=\"Gtk"
  "Grid\" id=\"grid2\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"row_spacing\">6</p"
  "roperty><property name=\"column_spacing\">12</property><child><object c"
  "lass=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"halign"
  "\">start</property><property name=\"label\" translatable=\"yes\">Trac_k"
  "ing mode:</property><property name=\"use_underline\">True</property></o"
  "bject><packing><property name=\"left_attach\">0</property><property nam"
  "e=\"top_attach\">0</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"label10\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"halign\">star"
  "t</property><property name=\"label\" translatable=\"yes\">_Rotation:</p"
  "roperty><property name=\"use_underline\">True</property></object><packi"
  "ng><property name=\"left_attach\">0</property><property name=\"top_atta"
  "ch\">1</property></packing></child><child><object class=\"GtkComboBox\""
  " id=\"wacom-mode\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"hexpand\">True</pro"
  "perty><property name=\"model\">wacom-mode-store</property><child><objec"
  "t class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><attributes><"
  "attribute name=\"text\">1</attribute></attributes></child></object><pac"
  "king><property name=\"left_attach\">1</property><property name=\"top_at"
  "tach\">0</property></packing></child><child><object class=\"GtkComboBox"
  "\" id=\"wacom-rotation\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"hexpand\">Tru"
  "e</property><property name=\"model\">wacom-rotation-store</property><ch"
  "ild><object class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><at"
  "tributes><attribute name=\"text\">1</attribute></attributes></child></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"top_attach\">1</property></packing></child></object></child></objec"
  "t></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label18"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label\" translatable=\"yes\">Genera"
  "l</property><property name=\"use_markup\">True</property><attributes><a"
  "ttribute name=\"weight\" value=\"bold\"/></attributes></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child></object><packing><property name=\"position\">2</propert"
  "y></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "wacom-label\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">Tab_let</property><property name=\"use_underline\">True</property>"
  "</object><packing><property name=\"position\">2</property><property nam"
  "e=\"tab_fill\">False</property></packing></child></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label1\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">_Devices</"
  "property><property name=\"use_underline\">True</property></object><pack"
  "ing><property name=\"tab_fill\">False</property></packing></child><chil"
  "d><object class=\"GtkBox\" id=\"vbox3\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"border_width\">12</property><property name=\"orientation\">vertical</"
  "property><property name=\"spacing\">18</property><child><object class=\""
  "GtkFrame\" id=\"frame3\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label_xalign\""
  ">0</property><property name=\"shadow_type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment3\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"top_padding\">6</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkBox\" id=\"vbox4\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"orientation\">vertical</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkLabel\" id=\"mouse-dnd-label\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"halign\">start</property><property name"
  "=\"label\" translatable=\"yes\">Th_reshold:</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">dnd-t"
  "hreshold-scale</property></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkScale\""
  " id=\"dnd-threshold-scale\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"tooltip_tex"
  "t\" translatable=\"yes\">The number of pixels the pointer must move bef"
  "ore a drag operation will start</property><property name=\"adjustment\""
  ">dnd-threshold</property><property name=\"digits\">0</property><propert"
  "y name=\"value_pos\">right</property></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">1</property></packing></child></object></child></ob"
  "ject></child><child type=\"label\"><object class=\"GtkLabel\" id=\"labe"
  "l6\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"label\" translatable=\"yes\">Drag"
  " and Drop</property><attributes><attribute name=\"weight\" value=\"bold"
  "\"/></attributes></object></child></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkFrame\" id=\"frame4\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label_xalign\""
  ">0</property><property name=\"shadow_type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment4\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"top_padding\">6</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkBox\" id=\"vbox5\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"orientation\">vertical</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkLabel\" id=\"dclick-time-label\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"halign\">start</property><property na"
  "me=\"label\" translatable=\"yes\">Ti_me:</property><property name=\"use"
  "_underline\">True</property><property name=\"mnemonic_widget\">dclick-t"
  "ime-scale</property></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkScale\" id="
  "\"dclick-time-scale\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"tooltip_text\" tr"
  "anslatable=\"yes\">Two mouse clicks in less than this length of time (i"
  "n milliseconds) will be considered a double click</property><property n"
  "ame=\"adjustment\">dclick-time</property><property name=\"digits\">0</p"
  "roperty><property name=\"value_pos\">right</property></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child><chi"
  "ld><object class=\"GtkLabel\" id=\"dclick-distance-label\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"halign\">start</property><property name=\"label\" "
  "translatable=\"yes\">D_istance:</property><property name=\"use_underlin"
  "e\">True</property><property name=\"mnemonic_widget\">dclick-distance-s"
  "cale</property></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">2"
  "</property></packing></child><child><object class=\"GtkScale\" id=\"dcl"
  "ick-distance-scale\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"tooltip_text\" tra"
  "nslatable=\"yes\">The mouse pointer cannot move farther than this dista"
  "nce between two clicks for them to be considered a double click</proper"
  "ty><property name=\"adjustment\">dclick-distance</property><property na"
  "me=\"digits\">0</property><property name=\"value_pos\">right</property>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">3</property></pa"
  "cking></child></object></child></object></child><child type=\"label\"><"
  "object class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">Double Click</property><attributes><attr"
  "ibute name=\"weight\" value=\"bold\"/></attributes></object></child></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"position\">1</property><"
  "/packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"la"
  "bel2\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">_B"
  "ehavior</property><property name=\"use_underline\">True</property></obj"
  "ect><packing><property name=\"position\">1</property><property name=\"t"
  "ab_fill\">False</property></packing></child><child><object class=\"GtkB"
  "ox\" id=\"themes-hbox\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"spacing\">12</property><child><object cl"
  "ass=\"GtkScrolledWindow\" id=\"scrolledwindow2\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"shadow_type\">etched-in</property><child><object class=\"GtkT"
  "reeView\" id=\"theme-treeview\"><property name=\"width_request\">200</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"headers_visible\">False</proper"
  "ty><child internal-child=\"selection\"><object class=\"GtkTreeSelection"
  "\" id=\"treeview-selection1\"/></child></object></child></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkBox\" id=\"vbox9\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"spacing\">18</p"
  "roperty><child><object class=\"GtkFrame\" id=\"frame5\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label_xalign\">0</property><property name=\"shadow_ty"
  "pe\">none</property><child><object class=\"GtkAlignment\" id=\"alignmen"
  "t5\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"top_padding\">6</property><proper"
  "ty name=\"left_padding\">12</property><child><object class=\"GtkBox\" i"
  "d=\"hbox7\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"spacing\">12</property><ch"
  "ild><object class=\"GtkLabel\" id=\"label21\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"halign\">start</property><property name=\"label\" translatable=\""
  "yes\">Cursor si_ze:</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"mnemonic_widget\">spin1</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkSpinButton\" id=\"spin1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"primary_icon_activatable\">False</property><property nam"
  "e=\"secondary_icon_activatable\">False</property><property name=\"adjus"
  "tment\">theme-cursor-size</property><property name=\"snap_to_ticks\">Tr"
  "ue</property><property name=\"numeric\">True</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">1</property></packing></child><"
  "/object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label20\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">Size</property><attributes><attribute name=\"weight\" "
  "value=\"bold\"/></attributes></object></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkFrame\" id=\"frame6\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment6\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"border_width\">0</property><property name=\"xscale\""
  ">0</property><property name=\"yscale\">0</property><property name=\"top"
  "_padding\">6</property><child><object class=\"GtkImage\" id=\"theme-pre"
  "view\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"stock\">gtk-missing-image</prop"
  "erty></object></child></object></child><child type=\"label\"><object cl"
  "ass=\"GtkLabel\" id=\"label22\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">Preview</property><attributes><attribute name=\"w"
  "eight\" value=\"bold\"/></attributes></object></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">True"
  "</property><property name=\"position\">1</property></packing></child></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object><packing><property name=\"position\">2</property>"
  "</packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"l"
  "abel3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">_"
  "Theme</property><property name=\"use_underline\">True</property></objec"
  "t><packing><property name=\"position\">2</property><property name=\"tab"
  "_fill\">False</property></packing></child></object><packing><property n"
  "ame=\"expand\">True</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child></object></chil"
  "d><action-widgets><action-widget response=\"-11\">button2</action-widge"
  "t><action-widget response=\"0\">button1</action-widget></action-widgets"
  "></object></interface>"
};

static const unsigned mouse_dialog_ui_length = 42605u;

